import { Stats } from "../classes/Stats";

export const sampleStats = new Stats({
    "recharge_base": 100,
    "hp_base": 13226,
    "atk_base": 871,
    "def_base": 876,
    "crit_dmg_base": 50,
    "crit_rate_base": 5,
    "dmg_electro": 2,
    "dmg_phys": 4,
    "dmg_normal": 8,
    "dmg_charged": 16,
    "dmg_skill": 32,
    "dmg_burst": 64,
    "mastery_base": 55,
    "atk_percent": 18,
});

export const sampleSettings = {
    "char_skill_attack": 8,
    "char_skill_elemental": 6,
    "char_skill_burst": 4,
    "char_level": 90,
    "char_ascension": 6,
    "char_constellation": 0,
    "char_id": 1,
    "char_name": "albedo",
    "char_element": "geo",
    "char_origin": "",
    "weapon_level": 90,
    "weapon_ascension": 6,
    "weapon_refine": 2,
    "weapon_type": "sword",
    "enemy_level": 90,
    "enemy_res_phys": 10,
    "enemy_res_anemo": 10,
    "enemy_res_cryo": 10,
    "enemy_res_geo": 10,
    "enemy_res_hydro": 10,
    "enemy_res_pyro": 10,
    "enemy_res_electro": 10,
    "enemy_res_dendro": 10,
    "common.enemy_status": 0,
    "enemy_type": "",
    "party_char_1": 0,
    "resonance_element_1": "",
    "party_char_2": 0,
    "resonance_element_2": "",
    "party_char_3": 0,
    "resonance_element_3": ""
};
