import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { ConditionNot } from "../../classes/Condition/Not";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";

export const Abyss = new DbObjectListSerialize({
    PyroAbyssMage: new DbObjectEnemy({
        name: 'pyro_abyss_mage',
        serializeId: 37,
        iconClass: "type-abyss enemy-icon-abyss-fire-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    CryoAbyssMage: new DbObjectEnemy({
        name: 'cryo_abyss_mage',
        serializeId: 38,
        iconClass: "type-abyss enemy-icon-abyss-ice-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HydroAbyssMage: new DbObjectEnemy({
        name: 'hydro_abyss_mage',
        serializeId: 39,
        iconClass: "type-abyss enemy-icon-abyss-water-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ElectroAbyssMage: new DbObjectEnemy({
        name: 'electro_abyss_mage',
        serializeId: 94,
        iconClass: "type-abyss enemy-icon-abyss-electric-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AbyssHerald: new DbObjectEnemy({
        name: 'abyss_herald',
        serializeId: 54,
        iconClass: "type-abyss enemy-icon-invoker-herald-water-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AbyssHeraldFrostFall: new DbObjectEnemy({
        name: 'abyss_herald_frost_fall',
        serializeId: 172,
        iconClass: "type-abyss enemy-icon-invoker-herald-ice",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AbyssLector: new DbObjectEnemy({
        name: 'abyss_lector',
        serializeId: 87,
        iconClass: "type-abyss enemy-icon-invoker-deacon-electric-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AbyssLectorPyro: new DbObjectEnemy({
        name: 'abyss_lector_pyro',
        serializeId: 122,
        iconClass: "type-abyss enemy-icon-invoker-deacon-fire",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    IniquitousBaptist  : new DbObjectEnemy({
        name: 'iniquitous_baptist',
        serializeId: 175,
        iconClass: "type-abyss enemy-icon-invoker-archdeacon",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RockfondRifthoundWhelp: new DbObjectEnemy({
        name: 'rockfond_rifthound_whelp',
        serializeId: 114,
        iconClass: "type-abyss enemy-icon-hound-kanis-rock",
        resistances: {
            phys: 20,
            pyro: 20,
            dendro: 20,
            hydro: 20,
            electro: 20,
            anemo: 20,
            cryo: 20,
            geo: 20,
        },
        conditions: [
            new ConditionBoolean({
                name: 'rifthound_devour',
                serializeId: 1,
                title: 'talent_name.rifthound_devour',
                description: 'talent_descr.rifthound_devour',
                stats: {
                    text_percent: 30,
                    enemy_res_geo: -30,
                },
            }),
        ],
    }),
    RockfondRifthound: new DbObjectEnemy({
        name: 'rockfond_rifthound',
        serializeId: 115,
        iconClass: "type-abyss enemy-icon-hound-riftstalker-rock",
        resistances: {
            phys: 25,
            pyro: 25,
            dendro: 25,
            hydro: 25,
            electro: 25,
            anemo: 25,
            cryo: 25,
            geo: 25,
        },
        conditions: [
            new ConditionBoolean({
                name: 'rifthound_devour',
                serializeId: 1,
                title: 'talent_name.rifthound_devour',
                description: 'talent_descr.rifthound_devour',
                stats: {
                    text_percent: 65,
                    enemy_res_geo: -65,
                },
            }),
        ],
    }),
    ThundercravenRifthoundWhelp: new DbObjectEnemy({
        name: 'thundercraven_rifthound_whelp',
        serializeId: 116,
        iconClass: "type-abyss enemy-icon-hound-kanis-electric",
        resistances: {
            phys: 20,
            pyro: 20,
            dendro: 20,
            hydro: 20,
            electro: 20,
            anemo: 20,
            cryo: 20,
            geo: 20,
        },
        conditions: [
            new ConditionBoolean({
                name: 'rifthound_devour',
                serializeId: 1,
                title: 'talent_name.rifthound_devour',
                description: 'talent_descr.rifthound_devour',
                stats: {
                    text_percent: 30,
                    enemy_res_electro: -30,
                },
            }),
        ],
    }),
    ThundercravenRifthound: new DbObjectEnemy({
        name: 'thundercraven_rifthound',
        serializeId: 117,
        iconClass: "type-abyss enemy-icon-hound-riftstalker-electric",
        resistances: {
            phys: 25,
            pyro: 25,
            dendro: 25,
            hydro: 25,
            electro: 25,
            anemo: 25,
            cryo: 25,
            geo: 25,
        },
        conditions: [
            new ConditionBoolean({
                name: 'rifthound_devour',
                serializeId: 1,
                title: 'talent_name.rifthound_devour',
                description: 'talent_descr.rifthound_devour',
                stats: {
                    text_percent: 65,
                    enemy_res_electro: -65,
                },
            }),
        ],
    }),
    GoldenWolflord: new DbObjectEnemy({
        name: 'golden_wolflord',
        serializeId: 118,
        iconClass: "type-abyss enemy-icon-hound-planelurker",
        resistances: {
            phys: 25,
            pyro: 25,
            dendro: 25,
            hydro: 25,
            electro: 25,
            anemo: 25,
            cryo: 25,
            geo: 25,
        },
        conditions: [
            new ConditionBoolean({
                name: 'rifthound_devour',
                serializeId: 1,
                title: 'talent_name.golden_wolflord_devour',
                description: 'talent_descr.golden_wolflord_devour',
                stats: {
                    text_percent: 45,
                    enemy_res_geo: -45,
                },
            }),
        ],
    }),
    ShadowyHuskStandardBearer: new DbObjectEnemy({
        name: 'shadowy_husk_standard_bearer',
        serializeId: 123,
        iconClass: "type-abyss enemy-icon-forlornvessel-strong-warbanner-fire",
        resistances: {
            phys: 30,
            pyro: 30,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ShadowyHuskLineBreaker: new DbObjectEnemy({
        name: 'shadowy_husk_line_breaker',
        serializeId: 124,
        iconClass: "type-abyss enemy-icon-forlornvessel-strong-lance-water",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 30,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ShadowyHuskDefender: new DbObjectEnemy({
        name: 'shadowy_husk_defender',
        serializeId: 125,
        iconClass: "type-abyss enemy-icon-forlornvessel-strong-chargebow-ice",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 30,
            geo: 10,
        },
    }),
    BlackSerpentKnightWindcutter: new DbObjectEnemy({
        name: 'black_serpent_knight_windcutter',
        serializeId: 127,
        iconClass: "type-abyss enemy-icon-darkwraith-strong-wind",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 50,
            cryo: 10,
            geo: 10,
        },
    }),
    BlackSerpentKnightRockbreakerAx: new DbObjectEnemy({
        name: 'black_serpent_knight_rockbreaker_ax',
        serializeId: 171,
        iconClass: "type-abyss enemy-icon-darkwraith-fat-rock",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
        conditions: [
            new ConditionBoolean({
                name: 'black_serpent_hits_shield',
                serializeId: 1,
                title: 'talent_name.black_serpent_hits_shield',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 50,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
        ],
    }),
    LargeShatterstoneBreacherPrimus: new DbObjectEnemy({
        name: 'large_shatterstone_breacher_primus',
        serializeId: 181,
        iconClass: "type-abyss enemy-icon-ovacua-order-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    ShatterstoneBreacherPrimus: new DbObjectEnemy({
        name: 'shatterstone_breacher_primus',
        serializeId: 182,
        iconClass: "type-abyss enemy-icon-ovacua-order-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 30,
        },
    }),
    LargeOvergrownBreacherPrimus: new DbObjectEnemy({
        name: 'large_overgrown_breacher_primus',
        serializeId: 183,
        iconClass: "type-abyss enemy-icon-ovacua-chaos-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 50,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    OvergrownBreacherPrimus: new DbObjectEnemy({
        name: 'overgrown_breacher_primus',
        serializeId: 184,
        iconClass: "type-abyss enemy-icon-ovacua-chaos-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 30,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    TenebrousMimiflora: new DbObjectEnemy({
        name: 'tenebrous_mimiflora',
        serializeId: 280,
        iconClass: "type-abyss enemy-icon-theabyss-rhizome",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    TenebrousPapillaTypeI : new DbObjectEnemy({
        name: 'tenebrous_papilla_type_1',
        serializeId: 282,
        iconClass: "type-abyss enemy-icon-theabyss-dendrite",
        resistances: {
            phys: 20,
            pyro: 20,
            dendro: 20,
            hydro: 20,
            electro: 20,
            anemo: 20,
            cryo: 20,
            geo: 20,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_weakened',
                serializeId: 1,
                title: 'talent_name.enemy_weakened',
                description: 'talent_descr.enemy_weakened',
                stats: {
                    enemy_res_phys: -70,
                    enemy_res_pyro: -70,
                    enemy_res_dendro: -70,
                    enemy_res_hydro: -70,
                    enemy_res_electro: -70,
                    enemy_res_anemo: -70,
                    enemy_res_cryo: -70,
                    enemy_res_geo: -70,
                },
            }),
            new ConditionBoolean({
                name: 'enemy_recovering',
                serializeId: 2,
                title: 'talent_name.enemy_recovering',
                description: 'talent_descr.enemy_recovering',
                stats: {
                    enemy_res_phys: -35,
                    enemy_res_pyro: -35,
                    enemy_res_dendro: -35,
                    enemy_res_hydro: -35,
                    enemy_res_electro: -35,
                    enemy_res_anemo: -35,
                    enemy_res_cryo: -35,
                    enemy_res_geo: -35,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'enemy_weakened'}),
                    ]),
                ],
            }),
            new ConditionBoolean({
                name: 'spiral_abyss_buff',
                serializeId: 3,
                title: 'talent_name.spiral_abyss_buff',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 50,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
        ],
    }),
});
