import { Condition } from "../../classes/Condition";
import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { ConditionDropdownElement } from "../../classes/Condition/Dropdown/Element";
import { ConditionNot } from "../../classes/Condition/Not";
import { ConditionOr } from "../../classes/Condition/Or";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";


const ruin_drake_conditions = [
    new ConditionDropdownElement({
        name: 'ruin_drake_infusion',
        serializeId: 1,
        title: 'talent_name.ruin_drake_infusion',
        description: 'talent_descr.ruin_drake_infusion',
        values: [
            {
                value: 'cryo',
                serializeId: 1,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_cryo: 40,
                        },
                    }),
                ],
            },
            {
                value: 'electro',
                serializeId: 2,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_electro: 40,
                        },
                    }),
                ],
            },
            {
                value: 'hydro',
                serializeId: 3,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_hydro: 40,
                        },
                    }),
                ],
            },
            {
                value: 'pyro',
                serializeId: 4,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_pyro: 40,
                        },
                    }),
                ],
            },
            {
                value: 'anemo',
                serializeId: 5,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_anemo: 40,
                        },
                    }),
                ],
            },
            {
                value: 'geo',
                serializeId: 6,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_geo: 40,
                        },
                    }),
                ],
            },
            {
                value: 'dendro',
                serializeId: 7,
                conditions: [
                    new Condition({
                        stats: {
                            enemy_res_dendro: 40,
                        },
                    }),
                ],
            },
        ],
    }),
];

export const Automaton = new DbObjectListSerialize({
    RuinGuard: new DbObjectEnemy({
        name: 'ruin_guard',
        serializeId: 51,
        iconClass: "type-automatons enemy-icon-defender-noner-01",
        resistances: {
            phys: 70,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinHunter: new DbObjectEnemy({
        name: 'ruin_hunter',
        serializeId: 52,
        iconClass: "type-automatons enemy-icon-formathr-none",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinGrader: new DbObjectEnemy({
        name: 'ruin_grader',
        serializeId: 53,
        iconClass: "type-automatons enemy-icon-konungmathr",
        resistances: {
            phys: 70,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinCruiser: new DbObjectEnemy({
        name: 'ruin_cruiser',
        serializeId: 99,
        iconClass: "type-automatons enemy-icon-apparatus-enigma-bionicdrone",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinDestroyer: new DbObjectEnemy({
        name: 'ruin_destroyer',
        serializeId: 100,
        iconClass: "type-automatons enemy-icon-apparatus-enigma-bionicflora",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinDefender: new DbObjectEnemy({
        name: 'ruin_defender',
        serializeId: 101,
        iconClass: "type-automatons enemy-icon-apparatus-enigma-bionicinsecta",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinScout: new DbObjectEnemy({
        name: 'ruin_scout',
        serializeId: 102,
        iconClass: "type-automatons enemy-icon-apparatus-enigma-bionicnettler",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    MaguuKenki: new DbObjectEnemy({
        name: 'maguu_kenki',
        serializeId: 89,
        iconClass: "type-automatons enemy-icon-samurai-ningyo",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    PerpetualMechanicalArray: new DbObjectEnemy({
        name: 'perpetual_mechanical_array',
        serializeId: 91,
        iconClass: "type-automatons enemy-icon-apparatus-perpetual",
        resistances: {
            phys: 70,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'automaton_stunned',
                serializeId: 1,
                title: 'talent_name.automaton_stunned',
                description: 'talent_descr.automaton_stunned',
                stats: {
                    enemy_res_phys: -50,
                    enemy_res_pyro: -50,
                    enemy_res_dendro: -50,
                    enemy_res_hydro: -50,
                    enemy_res_electro: -50,
                    enemy_res_anemo: -50,
                    enemy_res_cryo: -50,
                    enemy_res_geo: -50,
                },
            }),
        ],
    }),
    RuinSerpent: new DbObjectEnemy({
        name: 'ruin_serpent',
        serializeId: 129,
        iconClass: "type-automatons enemy-icon-nithhoggr-none",
        resistances: {
            phys: 70,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RuinDrakeEarthguard: new DbObjectEnemy({
        name: 'ruin_drake_earthguard',
        serializeId: 131,
        iconClass: "type-automatons enemy-icon-ruin-drake",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: ruin_drake_conditions,
    }),
    RuinDrakeSkywatch: new DbObjectEnemy({
        name: 'ruin_drake_skywatch',
        serializeId: 132,
        iconClass: "type-automatons enemy-icon-ruin-drake",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: ruin_drake_conditions,
    }),
    AeonblightDrake: new DbObjectEnemy({
        name: 'aeonblight_drake',
        serializeId: 152,
        iconClass: 'type-automatons enemy-icon-gargoyle-fafnir',
        resistances: {
            phys: 70,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionDropdownElement({
                name: 'aeonblight_drake_infusion',
                serializeId: 1,
                title: 'talent_name.ruin_drake_infusion',
                description: 'talent_descr.aeonblight_drake_infusion',
                values: [
                    {
                        value: 'cryo',
                        serializeId: 1,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_cryo: 60,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'electro',
                        serializeId: 2,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_electro: 60,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'hydro',
                        serializeId: 3,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_hydro: 60,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'pyro',
                        serializeId: 4,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_pyro: 60,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'anemo',
                        serializeId: 5,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_anemo: 60,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'geo',
                        serializeId: 6,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_geo: 60,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'dendro',
                        serializeId: 7,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_dendro: 60,
                                },
                            }),
                        ],
                    },
                ],
            }),
        ],
    }),
    PrimalConstructRepulsor: new DbObjectEnemy({
        name: 'primal_construct_repulsor',
        serializeId: 153,
        iconClass: 'type-automatons enemy-icon-monolith-ordinator',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'automaton_invisible',
                serializeId: 1,
                title: 'talent_name.automaton_invisible',
                description: 'talent_descr.automaton_invisible',
                stats: {
                    enemy_res_phys: 50,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
        ],
    }),
    PrimalConstructProspector: new DbObjectEnemy({
        name: 'primal_construct_prospector',
        serializeId: 154,
        iconClass: 'type-automatons enemy-icon-monolith-ordinator',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'automaton_invisible',
                serializeId: 1,
                title: 'talent_name.automaton_invisible',
                description: 'talent_descr.automaton_invisible',
                stats: {
                    enemy_res_phys: 50,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
        ],
    }),
    PrimalConstructReshaper: new DbObjectEnemy({
        name: 'primal_construct_reshaper',
        serializeId: 155,
        iconClass: 'type-automatons enemy-icon-monolith-ordinator',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'automaton_invisible',
                serializeId: 1,
                title: 'talent_name.automaton_invisible',
                description: 'talent_descr.automaton_invisible',
                stats: {
                    enemy_res_phys: 50,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
        ],
    }),
    AlgorithmMatrix: new DbObjectEnemy({
        name: 'algorithm_matrix',
        serializeId: 156,
        iconClass: 'type-automatons enemy-icon-monolith-starchild',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'automaton_invisible',
                serializeId: 1,
                title: 'talent_name.automaton_invisible',
                description: 'talent_descr.automaton_invisible',
                stats: {
                    enemy_res_phys: 200,
                    enemy_res_pyro: 200,
                    enemy_res_dendro: 200,
                    enemy_res_hydro: 200,
                    enemy_res_electro: 200,
                    enemy_res_anemo: 200,
                    enemy_res_cryo: 200,
                    enemy_res_geo: 200,
                },
            }),
            new ConditionBoolean({
                name: 'boss_begin_fight',
                serializeId: 2,
                title: 'talent_name.boss_begin_fight',
                description: 'talent_descr.boss_begin_fight',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'automaton_invisible'}),
                    ]),
                ],
            }),
        ],
    }),
    GeologicalSurveyMek: new DbObjectEnemy({
        name: 'geological_survey_mek',
        serializeId: 185,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-probe',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ReconLogMek: new DbObjectEnemy({
        name: 'recon_log_mek',
        serializeId: 186,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-sentry',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ArithmeticEnhancerMek: new DbObjectEnemy({
        name: 'arithmetic_enhancer_mek',
        serializeId: 187,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-pylon',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    UnderwaterSurveyMek: new DbObjectEnemy({
        name: 'underwater_survey_mek',
        serializeId: 188,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-recon',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    UnderwaterPatrolMek: new DbObjectEnemy({
        name: 'underwater_patrol_mek',
        serializeId: 189,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-nautilus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    NimbleHarvesterMek: new DbObjectEnemy({
        name: 'nimble_harvester_mek',
        serializeId: 190,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-assimilator',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AssaultSpecialistMek: new DbObjectEnemy({
        name: 'assault_specialist_mek',
        serializeId: 191,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-ruggiero-01',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    SuppressionSpecialistMek: new DbObjectEnemy({
        name: 'suppression_specialist_mek',
        serializeId: 192,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-ruggiero-02',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AnnihilationSpecialistMek: new DbObjectEnemy({
        name: 'annihilation_specialist_mek',
        serializeId: 193,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-bradamante',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AreaAlertMek: new DbObjectEnemy({
        name: 'area_alert_mek',
        serializeId: 194,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-lengthshifter',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ConstructionSpecialistMek: new DbObjectEnemy({
        name: 'construction_specialist_mek',
        serializeId: 195,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-excavator',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    IcewindSuite: new DbObjectEnemy({
        name: 'icewind_suite',
        serializeId: 196,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-nutcracker',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 70,
            cryo: 70,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'boss_begin_fight',
                serializeId: 1,
                title: 'talent_name.boss_begin_fight',
                description: 'talent_descr.boss_begin_fight',
                stats: {
                    enemy_res_phys: 300,
                    enemy_res_pyro: 300,
                    enemy_res_dendro: 300,
                    enemy_res_hydro: 300,
                    enemy_res_electro: 300,
                    enemy_res_anemo: 300,
                    enemy_res_cryo: 300,
                    enemy_res_geo: 300,
                },
            }),
            new ConditionBoolean({
                name: 'icewind_suite_climax',
                serializeId: 2,
                title: 'talent_name.icewind_suite_climax',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 25,
                    enemy_res_pyro: 25,
                    enemy_res_dendro: 25,
                    enemy_res_hydro: 25,
                    enemy_res_electro: 25,
                    enemy_res_anemo: 25,
                    enemy_res_cryo: 25,
                    enemy_res_geo: 25,
                },
            }),
        ],
    }),
    DeepwaterAssaultMek: new DbObjectEnemy({
        name: 'deepwater_assault_mek',
        serializeId: 211,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-frigate',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ExperimentalFieldGenerator: new DbObjectEnemy({
        name: 'experimental_field_generator',
        serializeId: 212,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-gravitas',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 70,
        },
        conditions: [
            new ConditionBoolean({
                name: 'field_generator_active',
                serializeId: 1,
                title: 'talent_name.field_generator_active',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 40,
                    enemy_res_pyro: 40,
                    enemy_res_dendro: 40,
                    enemy_res_hydro: 40,
                    enemy_res_electro: 40,
                    enemy_res_anemo: 40,
                    enemy_res_cryo: 40,
                    enemy_res_geo: 40,
                },
            }),
        ],
    }),
    SecretSourceAutomatonHunterSeeker: new DbObjectEnemy({
        name: 'secret_source_automaton_hunter_seeker',
        serializeId: 229,
        iconClass: 'type-automatons enemy-icon-toothtrap',
        resistances: {
            phys: 50,
            pyro: 50,
            dendro: 50,
            hydro: 50,
            electro: 50,
            anemo: 50,
            cryo: 50,
            geo: 50,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_stunned',
                serializeId: 1,
                title: 'talent_name.enemy_stunned',
                description: 'talent_descr.enemy_stunned_res',
                stats: {
                    enemy_res_phys: -40,
                    enemy_res_pyro: -40,
                    enemy_res_dendro: -40,
                    enemy_res_hydro: -40,
                    enemy_res_electro: -40,
                    enemy_res_anemo: -40,
                    enemy_res_cryo: -40,
                    enemy_res_geo: -40,
                },
            }),
        ],
    }),
    SecretSourceAutomatonConfigurationDevice: new DbObjectEnemy({
        name: 'secret_source_automaton_configuration_device',
        serializeId: 281,
        iconClass: 'type-automatons enemy-icon-dragonclaw',
        resistances: {
            phys: 60,
            pyro: 60,
            dendro: 60,
            hydro: 60,
            electro: 60,
            anemo: 60,
            cryo: 60,
            geo: 60,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_weakened',
                serializeId: 1,
                title: 'talent_name.enemy_weakened',
                description: 'talent_descr.enemy_weakened',
                stats: {
                    enemy_res_phys: -90,
                    enemy_res_pyro: -90,
                    enemy_res_dendro: -90,
                    enemy_res_hydro: -90,
                    enemy_res_electro: -90,
                    enemy_res_anemo: -90,
                    enemy_res_cryo: -90,
                    enemy_res_geo: -90,
                },
            }),
        ],
    }),
    SecretSourceAutomatonOverseerDevice: new DbObjectEnemy({
        name: 'secret_source_automaton_overseer_device',
        serializeId: 323,
        iconClass: 'type-automatons enemy-icon-dragoncollar',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'overseer_device_sweeper_mode',
                serializeId: 1,
                title: 'talent_name.overseer_device_sweeper_mode',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 200,
                    enemy_res_pyro: 200,
                    enemy_res_dendro: 200,
                    enemy_res_hydro: 200,
                    enemy_res_electro: 200,
                    enemy_res_anemo: 200,
                    enemy_res_cryo: 200,
                    enemy_res_geo: 200,
                },
            }),
            new ConditionBoolean({
                name: 'overseer_device_flow_momentum',
                serializeId: 2,
                title: 'talent_name.overseer_device_flow_momentum',
                description: 'talent_descr.debuff_all_resistances',
                stats: {
                    enemy_res_phys: -40,
                    enemy_res_pyro: -40,
                    enemy_res_dendro: -40,
                    enemy_res_hydro: -40,
                    enemy_res_electro: -40,
                    enemy_res_anemo: -40,
                    enemy_res_cryo: -40,
                    enemy_res_geo: -40,
                },
                condition: new ConditionNot([
                    new ConditionBoolean({name: 'overseer_device_sweeper_mode'}),
                ]),
            }),
            new ConditionBoolean({
                name: 'overseer_device_counterstrike_mode',
                serializeId: 3,
                title: 'talent_name.overseer_device_counterstrike_mode',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 40,
                    enemy_res_pyro: 40,
                    enemy_res_dendro: 40,
                    enemy_res_hydro: 40,
                    enemy_res_electro: 40,
                    enemy_res_anemo: 40,
                    enemy_res_cryo: 40,
                    enemy_res_geo: 40,
                },
                condition: new ConditionNot([
                    new ConditionOr([
                        new ConditionBoolean({name: 'overseer_device_sweeper_mode'}),
                        new ConditionBoolean({name: 'overseer_device_flow_momentum'}),
                    ]),
                ]),
            }),
        ],
    }),
});



