import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";

export const Elemental = new DbObjectListSerialize({
    DendroSlime: new DbObjectEnemy({
        name: 'dendro_slime',
        serializeId: 25,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-grass-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_dendro: 1,
        },
    }),
    AnemoSlime: new DbObjectEnemy({
        name: 'anemo_slime',
        serializeId: 26,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-wind-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_anemo: 1,
        },
    }),
    ElectroSlime: new DbObjectEnemy({
        name: 'electro_slime',
        serializeId: 27,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-electric-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_electro: 1,
        },
    }),
    CryoSlime: new DbObjectEnemy({
        name: 'cryo_slime',
        serializeId: 28,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-ice-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_cryo: 1,
        },
    }),
    HydroSlime: new DbObjectEnemy({
        name: 'hydro_slime',
        serializeId: 29,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-water-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
    }),
    GeoSlime: new DbObjectEnemy({
        name: 'geo_slime',
        serializeId: 30,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-rock-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_geo: 1,
        },
    }),
    PyroSlime: new DbObjectEnemy({
        name: 'pyro_slime',
        serializeId: 31,
        type: 'slime',
        iconClass: "type-elemental enemy-icon-slime-fire-02",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_pyro: 1,
        },
    }),
    EyeoftheStorm: new DbObjectEnemy({
        name: 'eye_of_the_storm',
        serializeId: 32,
        iconClass: "type-elemental enemy-icon-elemental-wind-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_anemo: 1,
        },
    }),
    ElectroHypostasis: new DbObjectEnemy({
        name: 'electro_hypostasis',
        serializeId: 33,
        iconClass: "type-elemental enemy-icon-effigy-electric",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_electro: 1,
        },
    }),
    AnemoHypostasis: new DbObjectEnemy({
        name: 'anemo_hypostasis',
        serializeId: 34,
        iconClass: "type-elemental enemy-icon-effigy-wind",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_anemo: 1,
        },
    }),
    GeoHypostasis: new DbObjectEnemy({
        name: 'geo_hypostasis',
        serializeId: 35,
        iconClass: "type-elemental enemy-icon-effigy-rock",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_geo: 1,
        },
    }),
    CryoHypostasis: new DbObjectEnemy({
        name: 'cryo_hypostasis',
        serializeId: 88,
        iconClass: "type-elemental enemy-icon-effigy-ice",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_cryo: 1,
        },
    }),
    PyroHypostasis: new DbObjectEnemy({
        name: 'pyro_hypostasis',
        serializeId: 90,
        iconClass: "type-elemental enemy-icon-effigy-fire",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_pyro: 1,
        },
    }),
    HydroHypostasis: new DbObjectEnemy({
        name: 'hydro_hypostasis',
        serializeId: 109,
        iconClass: "type-elemental enemy-icon-effigy-water",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
    }),
    DendroHypostasis: new DbObjectEnemy({
        name: 'dendro_hypostasis',
        serializeId: 164,
        iconClass: "type-elemental enemy-icon-effigy-grass",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_dendro: 1,
        },
    }),
    HydroSpecter: new DbObjectEnemy({
        name: 'hydro_specter',
        serializeId: 111,
        iconClass: "type-elemental enemy-icon-sylph-water-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
    }),
    GeoSpecter: new DbObjectEnemy({
        name: 'geo_specter',
        serializeId: 112,
        iconClass: "type-elemental enemy-icon-sylph-rock-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_geo: 1,
        },
    }),
    AnemoSpecter: new DbObjectEnemy({
        name: 'anemo_specter',
        serializeId: 113,
        iconClass: "type-elemental enemy-icon-sylph-wind-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_anemo: 1,
        },
    }),
    CryoSpecter: new DbObjectEnemy({
        name: 'cryo_specter',
        serializeId: 119,
        iconClass: "type-elemental enemy-icon-sylph-ice-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_cryo: 1,
        },
    }),
    ElectroSpecter: new DbObjectEnemy({
        name: 'electro_specter',
        serializeId: 121,
        iconClass: "type-elemental enemy-icon-sylph-electric-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_electro: 1,
        },
    }),
    PyroSpecter: new DbObjectEnemy({
        name: 'pyro_specter',
        serializeId: 120,
        iconClass: "type-elemental enemy-icon-sylph-fire-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_pyro: 1,
        },
    }),
    DendroSpecter: new DbObjectEnemy({
        name: 'dendro_specter',
        serializeId: 130,
        iconClass: "type-elemental enemy-icon-dendro-specter",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_dendro: 1,
        },
    }),
    Oceanid: new DbObjectEnemy({
        name: 'oceanid',
        serializeId: 36,
        iconClass: "type-elemental enemy-icon-oceanid",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
    }),
    ThunderManifestation: new DbObjectEnemy({
        name: 'thunder_manifestation',
        serializeId: 110,
        iconClass: "type-elemental enemy-icon-raijin",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_electro: 1,
        },
    }),
    TaintedWaterSplittingPhantasm: new DbObjectEnemy({
        name: 'tainted_water_splitting_phantasm',
        serializeId: 179,
        iconClass: "type-elemental enemy-icon-necalevia-normal",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
    }),
    TaintedWaterSpoutingPhantasm: new DbObjectEnemy({
        name: 'tainted_water_spouting_phantasm',
        serializeId: 180,
        iconClass: "type-elemental enemy-icon-necalevia-big",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
    }),
    HydroTulpa: new DbObjectEnemy({
        name: 'hydro_tulpa',
        serializeId: 214,
        iconClass: "type-elemental enemy-icon-narcissusborn-normal-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
        },
        conditions: [
            new ConditionBoolean({
                name: 'hydro_tulpa_rage',
                serializeId: 1,
                title: 'talent_name.hydro_tulpa_rage',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 45,
                    enemy_res_pyro: 45,
                    enemy_res_dendro: 45,
                    enemy_res_hydro: 45,
                    enemy_res_electro: 45,
                    enemy_res_anemo: 45,
                    enemy_res_cryo: 45,
                    enemy_res_geo: 45,
                },
            }),
        ],
    }),
});
