import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";

export const Fatui = new DbObjectListSerialize({
    CryogunnerLegionnaire: new DbObjectEnemy({
        name: 'fatui_cryogunner_legionnaire',
        serializeId: 42,
        iconClass: "type-fatui enemy-icon-skirmisher-male-fat-spraygun-ice-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_shield',
                serializeId: 1,
                title: 'talent_name.fatiu_shield',
                description: 'talent_descr.fatiu_shield',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    HydrogunnerLegionnaire: new DbObjectEnemy({
        name: 'fatui_hydrogunner_legionnaire',
        serializeId: 43,
        iconClass: "type-fatui enemy-icon-skirmisher-male-fat-spraygun-water-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_shield',
                serializeId: 1,
                title: 'talent_name.fatiu_shield',
                description: 'talent_descr.fatiu_shield',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    ElectrohammerVanguard: new DbObjectEnemy({
        name: 'fatui_electrohammer_vanguard',
        serializeId: 44,
        iconClass: "type-fatui enemy-icon-skirmisher-male-strong-greathammer-electric-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_shield',
                serializeId: 1,
                title: 'talent_name.fatiu_shield',
                description: 'talent_descr.fatiu_shield',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    GeochanterBracer: new DbObjectEnemy({
        name: 'fatui_geochanter_bracer',
        serializeId: 45,
        iconClass: "type-fatui enemy-icon-skirmisher-male-standard-staff-rock-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_shield',
                serializeId: 1,
                title: 'talent_name.fatiu_shield',
                description: 'talent_descr.fatiu_shield',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    AnemoboxerVanguard: new DbObjectEnemy({
        name: 'fatui_anemoboxer_vanguard',
        serializeId: 46,
        iconClass: "type-fatui enemy-icon-skirmisher-male-strong-gloves-wind-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_shield',
                serializeId: 1,
                title: 'talent_name.fatiu_shield',
                description: 'talent_descr.fatiu_shield',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    PyroslingerBracer: new DbObjectEnemy({
        name: 'fatui_pyroslinger_bracer',
        serializeId: 47,
        iconClass: "type-fatui enemy-icon-skirmisher-male-standard-rifle-fire-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_shield',
                serializeId: 1,
                title: 'talent_name.fatiu_shield',
                description: 'talent_descr.fatiu_shield',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    PyroAgent: new DbObjectEnemy({
        name: 'fatui_pyro_agent',
        serializeId: 48,
        iconClass: "type-fatui enemy-icon-fatuus-fire-01",
        resistances: {
            phys: -20,
            pyro: 50,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ElectroCicinMage: new DbObjectEnemy({
        name: 'fatui_electro_cicin_mage',
        serializeId: 49,
        iconClass: "type-fatui enemy-icon-fatuus-summoner-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 50,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    CryoCicinMage: new DbObjectEnemy({
        name: 'fatui_cryo_cicin_mage',
        serializeId: 50,
        iconClass: "type-fatui enemy-icon-fatuus-mage-ice-01",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    MirrorMaiden: new DbObjectEnemy({
        name: 'fatui_mirror_maiden',
        serializeId: 93,
        iconClass: "type-fatui enemy-icon-fatuus-maiden-water",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),

    FrostOperative: new DbObjectEnemy({
        name: 'frost_operative',
        serializeId: 208,
        iconClass: "type-fatui enemy-icon-fatuus-escadron-ice",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    WindOperative: new DbObjectEnemy({
        name: 'wind_operative',
        serializeId: 209,
        iconClass: "type-fatui enemy-icon-fatuus-escadron-wind",
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 50,
            cryo: 10,
            geo: 10,
        },
    }),
});
