import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";

export const Hilichurl = new DbObjectListSerialize({
    Hilichurl: new DbObjectEnemy({
        name: 'hilichurl',
        serializeId: 1,
        iconClass: "type-hilichurls enemy-icon-hili-none-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlFighter: new DbObjectEnemy({
        name: 'hilichurl_fighter',
        serializeId: 2,
        iconClass: "type-hilichurls enemy-icon-hili-none-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlBerserker: new DbObjectEnemy({
        name: 'hilichurl_berserker',
        serializeId: 3,
        iconClass: "type-hilichurls enemy-icon-hili-fire-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlGuardWoodenShield: new DbObjectEnemy({
        name: 'hilichurl_guard_wooden_shield',
        serializeId: 4,
        iconClass: "type-hilichurls enemy-icon-hili-none-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlGuardRockShield: new DbObjectEnemy({
        name: 'hilichurl_guard_rock_shield',
        serializeId: 5,
        iconClass: "type-hilichurls enemy-icon-hili-none-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlGuardIceShield: new DbObjectEnemy({
        name: 'hilichurl_guard_ice_shield',
        serializeId: 6,
        iconClass: "type-hilichurls enemy-icon-hili-none-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlGrenadierPyro: new DbObjectEnemy({
        name: 'hilichurl_grenadier_pyro',
        serializeId: 7,
        iconClass: "type-hilichurls enemy-icon-hili-fire-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlGrenadierCryo: new DbObjectEnemy({
        name: 'hilichurl_grenadier_cryo',
        serializeId: 8,
        iconClass: "type-hilichurls enemy-icon-hili-ice-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlGrenadierElectro: new DbObjectEnemy({
        name: 'hilichurl_grenadier_electro',
        serializeId: 95,
        iconClass: "type-hilichurls enemy-icon-hili-electric-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlShooter: new DbObjectEnemy({
        name: 'hilichurl_shooter',
        serializeId: 9,
        iconClass: "type-hilichurls enemy-icon-hili-ice-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlShooterElectro: new DbObjectEnemy({
        name: 'hilichurl_shooter_electro',
        serializeId: 10,
        iconClass: "type-hilichurls enemy-icon-hili-electric-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlShooterCryo: new DbObjectEnemy({
        name: 'hilichurl_shooter_cryo',
        serializeId: 11,
        iconClass: "type-hilichurls enemy-icon-hili-ice-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HilichurlShooterPyro: new DbObjectEnemy({
        name: 'hilichurl_shooter_pyro',
        serializeId: 12,
        iconClass: "type-hilichurls enemy-icon-hili-fire-range",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    UnusualHilichurl: new DbObjectEnemy({
        name: 'unusual_hilichurl',
        serializeId: 13,
        iconClass: "type-hilichurls enemy-icon-hili-wei",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    SamachurlAnemo: new DbObjectEnemy({
        name: 'samachurl_anemo',
        serializeId: 14,
        iconClass: "type-hilichurls enemy-icon-shaman-wind-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 50,
            cryo: 10,
            geo: 10,
        },
    }),
    SamachurlGeo: new DbObjectEnemy({
        name: 'samachurl_geo',
        serializeId: 15,
        iconClass: "type-hilichurls enemy-icon-shaman-rock-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    SamachurlDendro: new DbObjectEnemy({
        name: 'samachurl_dendro',
        serializeId: 16,
        iconClass: "type-hilichurls enemy-icon-shaman-grass-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 50,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    SamachurlHydro: new DbObjectEnemy({
        name: 'samachurl_hydro',
        serializeId: 17,
        iconClass: "type-hilichurls enemy-icon-shaman-water-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    SamachurlCryo: new DbObjectEnemy({
        name: 'samachurl_cryo',
        serializeId: 18,
        iconClass: "type-hilichurls enemy-icon-shaman-ice-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    SamachurlElectro: new DbObjectEnemy({
        name: 'samachurl_electro',
        serializeId: 98,
        iconClass: "type-hilichurls enemy-icon-shaman-electric-01",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 50,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    MitachurlWoodenShieldwall: new DbObjectEnemy({
        name: 'mitachurl_wooden_shieldwall',
        serializeId: 19,
        iconClass: "type-hilichurls enemy-icon-brute-none-01",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    MitachurlRockShieldwall: new DbObjectEnemy({
        name: 'mitachurl_rock_shieldwall',
        serializeId: 20,
        iconClass: "type-hilichurls enemy-icon-brute-none-01",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    MitachurlIceShieldwall: new DbObjectEnemy({
        name: 'mitachurl_ice_shieldwall',
        serializeId: 21,
        iconClass: "type-hilichurls enemy-icon-brute-none-01",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    MitachurlBlazingAxe: new DbObjectEnemy({
        name: 'mitachurl_blazing_axe',
        serializeId: 22,
        iconClass: "type-hilichurls enemy-icon-brute-none-01",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    MitachurlCracklingAxe: new DbObjectEnemy({
        name: 'mitachurl_crackling_axe',
        serializeId: 96,
        iconClass: "type-hilichurls enemy-icon-brute-none-01",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    LawachurlStonehide: new DbObjectEnemy({
        name: 'lawachurl_stonehide',
        serializeId: 23,
        iconClass: "type-hilichurls enemy-icon-brute-rock-none",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 70,
        },
    }),
    LawachurlFrostarm: new DbObjectEnemy({
        name: 'lawachurl_frostarm',
        serializeId: 24,
        iconClass: "type-hilichurls enemy-icon-brute-ice-01",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 70,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'mitachurl_shield',
                serializeId: 1,
                title: 'talent_name.mitachurl_shield',
                description: 'talent_descr.mitachurl_shield',
                stats: {
                    dmg_all: -80,
                },
            }),
        ],
    }),
    LawachurlThunderhelm: new DbObjectEnemy({
        name: 'lawachurl_thunderhelm',
        serializeId: 97,
        iconClass: "type-hilichurls enemy-icon-brute-electric-01",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 70,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),


    HydroHilichurlRogue: new DbObjectEnemy({
        name: 'hydro_hilichurl_rogue',
        serializeId: 173,
        iconClass: "type-hilichurls enemy-icon-hilistray-water",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    AnemoHilichurlRogue : new DbObjectEnemy({
        name: 'anemo_hilichurl_rogue',
        serializeId: 174,
        iconClass: "type-hilichurls enemy-icon-hilistray-wind",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 50,
            cryo: 10,
            geo: 10,
        },
    }),
});
