import { Condition } from '../../classes/Condition';
import { ConditionBoolean } from '../../classes/Condition/Boolean';
import { ConditionDropdownElement } from '../../classes/Condition/Dropdown/Element';
import { ConditionStacksNumber } from '../../classes/Condition/Stacks/Number';
import { DbObjectEnemy } from '../../classes/DbObject/Enemy';
import { DbObjectListSerialize } from '../../classes/DbObject/List/Serialize';
import { StatTable } from '../../classes/StatTable';

const fatuiShield = new ConditionBoolean({
    name: 'fatiu_shield',
    serializeId: 1,
    title: 'talent_name.fatiu_shield',
    description: 'talent_descr.fatiu_shield',
    stats: {
        enemy_res_phys: 100,
        enemy_res_pyro: 100,
        enemy_res_dendro: 100,
        enemy_res_hydro: 100,
        enemy_res_electro: 100,
        enemy_res_anemo: 100,
        enemy_res_cryo: 100,
        enemy_res_geo: 100,
    },
});

export const LocalLegends = new DbObjectListSerialize({
    RuleroftheChizhangMountainsYiji: new DbObjectEnemy({
        name: 'ruler_of_the_chizhang_mountains_yiji',
        serializeId: 266,
        iconClass: 'type-magical enemy-icon-drake-rock',
        resistances: {
            phys: 30,
            pyro: 70,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    RuleroftheChizhangMountainsTianyu: new DbObjectEnemy({
        name: 'ruler_of_the_chizhang_mountains_tianyu',
        serializeId: 267,
        iconClass: 'type-magical enemy-icon-drake-rock',
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 70,
            geo: 50,
        },
    }),
    NinianneoftheLake: new DbObjectEnemy({
        name: 'ninianne_of_the_lake',
        serializeId: 258,
        iconClass: 'type-elemental enemy-icon-necalevia-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
            enemy_immune_frozen: 1,
        },
    }),
    VivianneoftheLake: new DbObjectEnemy({
        name: 'vivianne_of_the_lake',
        serializeId: 259,
        iconClass: 'type-elemental enemy-icon-necalevia-big',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        settings: {
            enemy_immune_hydro: 1,
            enemy_immune_frozen: 1,
        },
    }),
    TheColdHand: new DbObjectEnemy({
        name: 'the_cold_hand',
        serializeId: 260,
        iconClass: 'type-fatui enemy-icon-fatuus-escadron-ice',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    DeianeiraofSnezhevna: new DbObjectEnemy({
        name: 'deianeira_of_snezhevna',
        serializeId: 261,
        iconClass: 'type-fatui enemy-icon-fatuus-escadron-wind',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 50,
            cryo: 10,
            geo: 10,
        },
    }),
    AutomatedSupercomputingFieldGenerator: new DbObjectEnemy({
        name: 'automated_supercomputing_field_generator',
        serializeId: 262,
        iconClass: 'type-automatons enemy-icon-machinaiustitia-pylon',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'regisvine_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 200,
                    enemy_res_pyro: 200,
                    enemy_res_dendro: 200,
                    enemy_res_hydro: 200,
                    enemy_res_electro: 200,
                    enemy_res_anemo: 200,
                    enemy_res_cryo: 200,
                    enemy_res_geo: 200,
                },
            }),
        ],
    }),
    Liam: new DbObjectEnemy({
        name: 'liam',
        serializeId: 263,
        iconClass: 'type-legend enemy-icon-liam',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RockyAvildsen: new DbObjectEnemy({
        name: 'rocky_avildsen',
        serializeId: 264,
        iconClass: 'type-legend enemy-icon-rockyavildsen',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Cineas: new DbObjectEnemy({
        name: 'cineas',
        serializeId: 265,
        iconClass: 'type-magical enemy-icon-drake-deepsea-water',
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 70,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'regisvine_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 80,
                    enemy_res_pyro: 80,
                    enemy_res_dendro: 80,
                    enemy_res_hydro: 80,
                    enemy_res_electro: 80,
                    enemy_res_anemo: 80,
                    enemy_res_cryo: 80,
                    enemy_res_geo: 80,
                },
            }),
        ],
    }),
    SapphoAmidsttheWaves: new DbObjectEnemy({
        name: 'sappho_amidst_the_waves',
        serializeId: 268,
        iconClass: 'type-human enemy-icon-tribalwarrior-slingshot-mosasaurus',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Cocijo: new DbObjectEnemy({
        name: 'cocijo',
        serializeId: 269,
        iconClass: 'type-legend enemy-icon-tortoise-electric',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    PolychromeTriStarsVasily: new DbObjectEnemy({
        name: 'polychrome_tri_stars_vasily',
        serializeId: 270,
        iconClass: 'type-fatui enemy-icon-fatuus-fire-01',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            fatuiShield,
        ],
    }),
    PolychromeTriStarsSidorenko: new DbObjectEnemy({
        name: 'polychrome_tri_stars_sidorenko',
        serializeId: 271,
        iconClass: 'type-fatui enemy-icon-skirmisher-male-fat-spraygun-ice-01',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            fatuiShield,
        ],
    }),
    PolychromeTriStarsNomokonov: new DbObjectEnemy({
        name: 'polychrome_tri_stars_nomokonov',
        serializeId: 272,
        iconClass: 'type-fatui enemy-icon-skirmisher-male-strong-greathammer-electric-01',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            fatuiShield,
        ],
    }),
    Balachko: new DbObjectEnemy({
        name: 'balachko',
        serializeId: 273,
        iconClass: 'type-fatui enemy-icon-fatuus-fire-01',
        resistances: {
            phys: -20,
            pyro: 70,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'fatiu_invisible',
                serializeId: 1,
                title: 'talent_name.fatiu_invisible',
                description: 'talent_descr.fatiu_invisible',
                stats: {
                    enemy_res_phys: 300,
                    enemy_res_pyro: 300,
                    enemy_res_dendro: 300,
                    enemy_res_hydro: 300,
                    enemy_res_electro: 300,
                    enemy_res_anemo: 300,
                    enemy_res_cryo: 300,
                    enemy_res_geo: 300,
                },
            }),
        ],
    }),
    HeNeverDies: new DbObjectEnemy({
        name: 'he_never_dies',
        serializeId: 274,
        iconClass: 'type-legend enemy-icon-he-never-dies-icon',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'hydro_tulpa_rage',
                serializeId: 1,
                title: 'talent_name.hydro_tulpa_rage',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 300,
                    enemy_res_pyro: 300,
                    enemy_res_dendro: 300,
                    enemy_res_hydro: 300,
                    enemy_res_electro: 300,
                    enemy_res_anemo: 300,
                    enemy_res_cryo: 300,
                    enemy_res_geo: 300,
                },
            }),
        ],
    }),
    IchcahuipillisAegis: new DbObjectEnemy({
        name: 'ichcahuipillis_aegis',
        serializeId: 275,
        iconClass: 'type-magical enemy-icon-wayob-hookwalker',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 50,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionStacksNumber({
                name: 'ichcahuipillis_aegis',
                serializeId: 1,
                title: 'talent_name.ichcahuipillis_aegis',
                description: 'talent_descr.ichcahuipillis_aegis',
                maxStacks: 15,
                showButtons: true,
                class: 'inputs-2digit',
                stats: [
                    new StatTable('dmg_all', [60]),
                ],
            }),
        ]
    }),
    AtlatlsBlessing: new DbObjectEnemy({
        name: 'atlatls_blessing',
        serializeId: 276,
        iconClass: 'type-magical enemy-icon-wayob-drillhead',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    CihuacoatlofChimericBone: new DbObjectEnemy({
        name: 'cihuacoatl_of_chimeric_bone',
        serializeId: 277,
        iconClass: 'type-human enemy-icon-tribalwarrior-launcher-hookwalker',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'hydro_tulpa_rage',
                serializeId: 1,
                title: 'talent_name.hydro_tulpa_rage',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    Tlatzacuilotl: new DbObjectEnemy({
        name: 'tlatzacuilotl',
        serializeId: 278,
        iconClass: 'type-human enemy-icon-tribalwarrior-powermaul-drillhead',
        resistances: {
            phys: 280,
            pyro: 310,
            dendro: 310,
            hydro: 310,
            electro: 310,
            anemo: 310,
            cryo: 310,
            geo: 310,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_stunned',
                serializeId: 1,
                title: 'talent_name.enemy_stunned',
                description: 'talent_descr.enemy_stunned_res',
                stats: {
                    enemy_res_phys: -300,
                    enemy_res_pyro: -300,
                    enemy_res_dendro: -300,
                    enemy_res_hydro: -300,
                    enemy_res_electro: -300,
                    enemy_res_anemo: -300,
                    enemy_res_cryo: -300,
                    enemy_res_geo: -300,
                },
            }),
        ],
    }),
    ChimallisShade: new DbObjectEnemy({
        name: 'chimallis_shade',
        serializeId: 279,
        iconClass: 'type-magical enemy-icon-wayob-mosasaurus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_stunned',
                serializeId: 1,
                title: 'talent_name.enemy_stunned',
                description: 'talent_descr.enemy_stunned_bonus',
                stats: {
                    dmg_all: 100,
                },
            }),
        ],
    }),
    Ironbeard: new DbObjectEnemy({
        name: 'ironbeard',
        serializeId: 312,
        iconClass: 'type-human enemy-icon-tribalwarrior-powermaul-flamingo',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    PotaposSolidarity: new DbObjectEnemy({
        name: 'potapos_solidarity',
        serializeId: 313,
        iconClass: 'type-magical enemy-icon-wayob-shamansaurus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    TupayosAid: new DbObjectEnemy({
        name: 'tupayos_aid',
        serializeId: 314,
        iconClass: 'type-magical enemy-icon-wayob-flamingo',
        resistances: {
            phys: 10,
            pyro: 50,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    SpiritOfTheFallenDawnstar: new DbObjectEnemy({
        name: 'spirit_of_the_fallen_dawnstar',
        serializeId: 315,
        iconClass: 'type-magical enemy-icon-natsaurus-shamansaurus-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    TupusLushness: new DbObjectEnemy({
        name: 'tupus_lushness',
        serializeId: 316,
        iconClass: 'type-magical enemy-icon-wayob-bisonsaurus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 50,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_thunderous_rebuke',
                serializeId: 1,
                title: 'talent_name.enemy_thunderous_rebuke',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 200,
                    enemy_res_pyro: 200,
                    enemy_res_dendro: 200,
                    enemy_res_hydro: 200,
                    enemy_res_electro: 200,
                    enemy_res_anemo: 200,
                    enemy_res_cryo: 200,
                    enemy_res_geo: 200,
                },
            }),
        ],
    }),
    Reji: new DbObjectEnemy({
        name: 'reji',
        serializeId: 317,
        iconClass: 'type-human enemy-icon-tribalwarrior-slingshot-bisonsaurus',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Bronzelock: new DbObjectEnemy({
        name: 'bronzelock',
        serializeId: 318,
        iconClass: 'type-automatons enemy-icon-ruin-drake',
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionDropdownElement({
                name: 'ruin_drake_infusion',
                serializeId: 1,
                title: 'talent_name.ruin_drake_infusion',
                description: 'talent_descr.legend_drake_infusion',
                values: [
                    {
                        value: 'cryo',
                        serializeId: 1,
                        conditions: [
                            new Condition({stats: {enemy_res_cryo: 120}}),
                        ],
                    },
                    {
                        value: 'electro',
                        serializeId: 2,
                        conditions: [
                            new Condition({stats: {enemy_res_electro: 120}}),
                        ],
                    },
                    {
                        value: 'hydro',
                        serializeId: 3,
                        conditions: [
                            new Condition({stats: {enemy_res_hydro: 120}}),
                        ],
                    },
                    {
                        value: 'pyro',
                        serializeId: 4,
                        conditions: [
                            new Condition({stats: {enemy_res_pyro: 120}}),
                        ],
                    },
                    {
                        value: 'anemo',
                        serializeId: 5,
                        conditions: [
                            new Condition({stats: {enemy_res_anemo: 120}}),
                        ],
                    },
                    {
                        value: 'geo',
                        serializeId: 6,
                        conditions: [
                            new Condition({stats: {enemy_res_geo: 120}}),
                        ],
                    },
                    {
                        value: 'dendro',
                        serializeId: 7,
                        conditions: [
                            new Condition({stats: {enemy_res_dendro: 120}}),
                        ],
                    },
                ],
            }),
        ],
    }),
    Rilai: new DbObjectEnemy({
        name: 'rilai',
        serializeId: 319,
        iconClass: 'type-human enemy-icon-tribalwarrior-launcher-shamansaurus',
        resistances: {
            phys: -20,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ThePeak: new DbObjectEnemy({
        name: 'the_peak',
        serializeId: 320,
        iconClass: 'type-magical enemy-icon-natsaurus-bisonsaurus-normal',
        resistances: {
            phys: 10,
            pyro: 50,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_horns_ignited',
                serializeId: 1,
                title: 'talent_name.enemy_horns_ignited',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    Infinitesimal: new DbObjectEnemy({
        name: 'infinitesimal',
        serializeId: 321,
        iconClass: 'type-magical enemy-icon-lava-solid',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
});
