import { Condition } from "../../classes/Condition";
import { ConditionAnd } from "../../classes/Condition/And";
import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { ConditionDropdownElement } from "../../classes/Condition/Dropdown/Element";
import { ConditionNot } from "../../classes/Condition/Not";
import { ConditionStatic } from "../../classes/Condition/Static";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";

const defaultRes = {
    phys: 10,
    pyro: 10,
    dendro: 10,
    hydro: 10,
    electro: 10,
    anemo: 10,
    cryo: 10,
    geo: 10,
};

let fontemer_aberrant_shielded = new ConditionBoolean({
    name: 'fontemer_aberrant_shielded',
    serializeId: 1,
    title: 'talent_name.fontemer_aberrant_shielded',
    description: 'talent_descr.fontemer_aberrant_shielded',
    stats: {
        enemy_res_phys: 60,
        enemy_res_pyro: 60,
        enemy_res_dendro: 60,
        enemy_res_hydro: 60,
        enemy_res_electro: 60,
        enemy_res_anemo: 60,
        enemy_res_cryo: 60,
        enemy_res_geo: 60,
    },
});

export const Magical = new DbObjectListSerialize({
    CryoWhopperflower: new DbObjectEnemy({
        name: 'cryo_whopperflower',
        serializeId: 40,
        iconClass: "type-magical enemy-icon-mimik-ice",
        resistances: {
            phys: 35,
            pyro: 35,
            dendro: 35,
            hydro: 35,
            electro: 35,
            anemo: 35,
            cryo: 75,
            geo: 35,
        },
        conditions: [
            new ConditionBoolean({
                name: 'whopperflower_stunned',
                serializeId: 1,
                title: 'talent_name.whopperflower_stunned',
                description: 'talent_descr.whopperflower_stunned',
                stats: {
                    enemy_res_phys: -25,
                    enemy_res_pyro: -25,
                    enemy_res_dendro: -25,
                    enemy_res_hydro: -25,
                    enemy_res_electro: -25,
                    enemy_res_anemo: -25,
                    enemy_res_cryo: -25,
                    enemy_res_geo: -25,
                },
            }),
        ],
    }),
    PyroWhopperflower: new DbObjectEnemy({
        name: 'pyro_whopperflower',
        serializeId: 41,
        iconClass: "type-magical enemy-icon-mimik-fire",
        resistances: {
            phys: 35,
            pyro: 75,
            dendro: 35,
            hydro: 35,
            electro: 35,
            anemo: 35,
            cryo: 35,
            geo: 35,
        },
        conditions: [
            new ConditionBoolean({
                name: 'whopperflower_stunned',
                serializeId: 1,
                title: 'talent_name.whopperflower_stunned',
                description: 'talent_descr.whopperflower_stunned',
                stats: {
                    enemy_res_phys: -25,
                    enemy_res_pyro: -25,
                    enemy_res_dendro: -25,
                    enemy_res_hydro: -25,
                    enemy_res_electro: -25,
                    enemy_res_anemo: -25,
                    enemy_res_cryo: -25,
                    enemy_res_geo: -25,
                },
            }),
        ],
    }),
    ElectroWhopperflower: new DbObjectEnemy({
        name: 'electro_whopperflower',
        serializeId: 92,
        iconClass: "type-magical enemy-icon-mimik-electric",
        resistances: {
            phys: 35,
            pyro: 35,
            dendro: 35,
            hydro: 35,
            electro: 75,
            anemo: 35,
            cryo: 35,
            geo: 35,
        },
        conditions: [
            new ConditionBoolean({
                name: 'whopperflower_stunned',
                serializeId: 1,
                title: 'talent_name.whopperflower_stunned',
                description: 'talent_descr.whopperflower_stunned',
                stats: {
                    enemy_res_phys: -25,
                    enemy_res_pyro: -25,
                    enemy_res_dendro: -25,
                    enemy_res_hydro: -25,
                    enemy_res_electro: -25,
                    enemy_res_anemo: -25,
                    enemy_res_cryo: -25,
                    enemy_res_geo: -25,
                },
            }),
        ],
    }),
    PyroRegisvine: new DbObjectEnemy({
        name: 'pyro_regisvine',
        serializeId: 75,
        iconClass: "type-magical enemy-icon-regisvine-fire",
        resistances: {
            phys: 30,
            pyro: 70,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'regisvine_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    CryoRegisvine: new DbObjectEnemy({
        name: 'cryo_regisvine',
        serializeId: 76,
        iconClass: "type-magical enemy-icon-regisvine-ice",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 70,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'regisvine_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 100,
                    enemy_res_pyro: 100,
                    enemy_res_dendro: 100,
                    enemy_res_hydro: 100,
                    enemy_res_electro: 100,
                    enemy_res_anemo: 100,
                    enemy_res_cryo: 100,
                    enemy_res_geo: 100,
                },
            }),
        ],
    }),
    ElectroRegisvine: new DbObjectEnemy({
        name: 'electro_regisvine',
        serializeId: 141,
        iconClass: "type-magical enemy-icon-electro-regisvine",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 70,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'regisvine_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 300,
                    enemy_res_pyro: 300,
                    enemy_res_dendro: 300,
                    enemy_res_hydro: 300,
                    enemy_res_electro: 300,
                    enemy_res_anemo: 300,
                    enemy_res_cryo: 300,
                    enemy_res_geo: 300,
                },
            }),
        ],
    }),
    GreatSnowboarKing: new DbObjectEnemy({
        name: 'great_snowboar_king',
        serializeId: 77,
        iconClass: "type-magical enemy-icon-boar-03",
        resistances: {
            phys: 50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 30,
            geo: 10,
        },
    }),
    Geovishap: new DbObjectEnemy({
        name: 'geovishap',
        serializeId: 66,
        iconClass: "type-magical enemy-icon-drake-rock",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
        conditions: [
            new ConditionDropdownElement({
                name: 'geovishap_infusion',
                serializeId: 1,
                title: 'talent_name.geovishap_infusion',
                description: 'talent_descr.geovishap_infusion',
                values: [
                    {
                        value: 'cryo',
                        serializeId: 1,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_cryo: 20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'electro',
                        serializeId: 2,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_electro: 20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'hydro',
                        serializeId: 3,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_hydro: 20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'pyro',
                        serializeId: 4,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_pyro: 20,
                                },
                            }),
                        ],
                    },
                ],
            }),
        ],
    }),
    GeovishapHatchling: new DbObjectEnemy({
        name: 'geovishap_hatchling',
        serializeId: 67,
        iconClass: "type-magical enemy-icon-wyrm-rock",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    PrimoGeovishap: new DbObjectEnemy({
        name: 'primo_geovishap',
        serializeId: 68,
        iconClass: "type-magical enemy-icon-drake-primo-rock",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
        conditions: [
            new ConditionDropdownElement({
                name: 'geovishap_infusion',
                serializeId: 1,
                title: 'talent_name.geovishap_infusion',
                description: 'talent_descr.geovishap_infusion',
                values: [
                    {
                        value: 'cryo',
                        serializeId: 1,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_cryo: 20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'electro',
                        serializeId: 2,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_electro: 20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'hydro',
                        serializeId: 3,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_hydro: 20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'pyro',
                        serializeId: 4,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_pyro: 20,
                                },
                            }),
                        ],
                    },
                ],
            }),
            new ConditionBoolean({
                name: 'geovishap_counter',
                serializeId: 2,
                title: 'talent_name.geovishap_counter',
                description: 'talent_descr.geovishap_counter',
                stats: {
                    enemy_res_phys: -50,
                    enemy_res_pyro: -50,
                    enemy_res_dendro: -50,
                    enemy_res_hydro: -50,
                    enemy_res_electro: -50,
                    enemy_res_anemo: -50,
                    enemy_res_cryo: -50,
                    enemy_res_geo: -50,
                }
            }),
        ],
    }),
    BathysmalVishapElectro: new DbObjectEnemy({
        name: 'bathysmal_vishap_electro',
        serializeId: 223,
        iconClass: "type-magical enemy-icon-drake-deepsea-electric",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 20,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionStatic({
                title: 'talent_name.bathysmal_vishap_hatchling',
                description: 'talent_descr.bathysmal_vishap_hatchling',
                subConditions: [
                    new ConditionBoolean({
                        name: 'bathysmal_vishap_large',
                        invert: true,
                    }),
                ],
            }),
            new ConditionBoolean({
                name: 'bathysmal_vishap_large',
                serializeId: 1,
                title: 'talent_name.bathysmal_vishap_large',
                description: 'talent_descr.bathysmal_vishap_large',
                stats: {
                    enemy_res_electro: 10,
                },
            }),
        ],
    }),
    BathysmalVishapHydro: new DbObjectEnemy({
        name: 'bathysmal_vishap_hydro',
        serializeId: 224,
        iconClass: "type-magical enemy-icon-drake-deepsea-water",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 20,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionStatic({
                title: 'talent_name.bathysmal_vishap_hatchling',
                description: 'talent_descr.bathysmal_vishap_hatchling',
                subConditions: [
                    new ConditionBoolean({
                        name: 'bathysmal_vishap_large',
                        invert: true,
                    }),
                ],
            }),
            new ConditionBoolean({
                name: 'bathysmal_vishap_large',
                serializeId: 1,
                title: 'talent_name.bathysmal_vishap_large',
                description: 'talent_descr.bathysmal_vishap_large',
                stats: {
                    enemy_res_hydro: 10,
                },
            }),
        ],
    }),
    BathysmalVishapCryo: new DbObjectEnemy({
        name: 'bathysmal_vishap_cryo',
        serializeId: 225,
        iconClass: "type-magical enemy-icon-drake-deepsea-ice",
        resistances: {
            phys: 30,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 20,
            geo: 10,
        },
        conditions: [
            new ConditionStatic({
                title: 'talent_name.bathysmal_vishap_hatchling',
                description: 'talent_descr.bathysmal_vishap_hatchling',
                subConditions: [
                    new ConditionBoolean({
                        name: 'bathysmal_vishap_large',
                        invert: true,
                    }),
                ],
            }),
            new ConditionBoolean({
                name: 'bathysmal_vishap_large',
                serializeId: 1,
                title: 'talent_name.bathysmal_vishap_large',
                description: 'talent_descr.bathysmal_vishap_large',
                stats: {
                    enemy_res_cryo: 10,
                },
            }),
        ],
    }),
    ElectroCicin: new DbObjectEnemy({
        name: 'electro_cicin',
        serializeId: 72,
        iconClass: "type-magical enemy-icon-cicin-thunder-01",
        resistances: {
            phys: -50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 50,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    HydroCicin: new DbObjectEnemy({
        name: 'hydro_cicin',
        serializeId: 73,
        iconClass: "type-magical enemy-icon-cicin-water-01",
        resistances: {
            phys: -50,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    CryoCicin: new DbObjectEnemy({
        name: 'cryo_cicin',
        serializeId: 74,
        iconClass: "type-magical enemy-icon-cicin-ice-01",
        resistances: {
            phys: -50,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    FloatingFungus: new DbObjectEnemy({
        name: 'floating_fungus',
        serializeId: 128,
        iconClass: "type-magical enemy-icon-fungus-un-gamma-water",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 20,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    FloatingDendroFungus: new DbObjectEnemy({
        name: 'floating_dendro_fungus',
        serializeId: 142,
        iconClass: "type-magical enemy-icon-floating-dendro-fungus",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 25,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    WhirlingElectroFungus: new DbObjectEnemy({
        name: 'whirling_electro_fungus',
        serializeId: 151,
        iconClass: "type-magical enemy-icon-whirling-electro-fungus",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 10,
            electro: 20,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    WhirlingCryoFungus: new DbObjectEnemy({
        name: 'whirling_cryo_fungus',
        serializeId: 143,
        iconClass: "type-magical enemy-icon-whirling-cryo-fungus",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 20,
            geo: 10,
        },
    }),
    StretchyPyroFungus: new DbObjectEnemy({
        name: 'stretchy_pyro_fungus',
        serializeId: 144,
        iconClass: "type-magical enemy-icon-stretchy-pyro-fungus",
        resistances: {
            phys: 10,
            pyro: 20,
            dendro: 20,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    StretchyAnemoFungus: new DbObjectEnemy({
        name: 'stretchy_anemo_fungus',
        serializeId: 145,
        iconClass: "type-magical enemy-icon-stretchy-anemo-fungus",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 10,
            electro: 10,
            anemo: 20,
            cryo: 10,
            geo: 10,
        },
    }),
    StretchyGeoFungus: new DbObjectEnemy({
        name: 'stretchy_geo_fungus',
        serializeId: 146,
        iconClass: "type-magical enemy-icon-stretchy-geo-fungus",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 20,
        },
    }),
    GroundedHydroshroom: new DbObjectEnemy({
        name: 'grounded_hydroshroom',
        serializeId: 147,
        iconClass: "type-magical enemy-icon-grounded-hydroshroom",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 30,
            hydro: 30,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    WingedDendroshroom: new DbObjectEnemy({
        name: 'winged_dendroshroom',
        serializeId: 148,
        iconClass: "type-magical enemy-icon-winged-dendroshroom",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 40,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    WingedCryoshroom: new DbObjectEnemy({
        name: 'winged_cryoshroom',
        serializeId: 149,
        iconClass: "type-magical enemy-icon-winged-cryoshroom",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 30,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 30,
            geo: 10,
        },
    }),
    JadeplumeTerrorshroom: new DbObjectEnemy({
        name: 'jadeplume_terrorshroom',
        serializeId: 150,
        iconClass: "type-magical enemy-icon-jadeplume-terrorshroom",
        resistances: {
            phys: 25,
            pyro: 25,
            dendro: 80,
            hydro: 25,
            electro: 25,
            anemo: 25,
            cryo: 25,
            geo: 25,
        },
        conditions: [
            new ConditionBoolean({
                name: 'terrorshroom_stunned',
                serializeId: 1,
                title: 'talent_name.terrorshroom_stunned',
                description: 'talent_descr.terrorshroom_stunned',
                stats: {
                    enemy_res_phys: -25,
                    enemy_res_pyro: -25,
                    enemy_res_dendro: -25,
                    enemy_res_hydro: -25,
                    enemy_res_electro: -25,
                    enemy_res_anemo: -25,
                    enemy_res_cryo: -25,
                    enemy_res_geo: -25,
                },
            }),
        ],
    }),
    FloatingAnemoFungus: new DbObjectEnemy({
        name: 'floating_anemo_fungus',
        serializeId: 159,
        iconClass: "type-magical enemy-icon-fungus-un-delta-wind",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 10,
            electro: 10,
            anemo: 20,
            cryo: 10,
            geo: 10,
        },
    }),
    WhirlingPyroFungus: new DbObjectEnemy({
        name: 'whirling_pyro_fungus',
        serializeId: 160,
        iconClass: "type-magical enemy-icon-fungus-trois-gamma-fire",
        resistances: {
            phys: 10,
            pyro: 20,
            dendro: 20,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    StretchyElectroFungus: new DbObjectEnemy({
        name: 'stretchy_electro_fungus',
        serializeId: 161,
        iconClass: "type-magical enemy-icon-fungus-deux-delta-electric",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 20,
            hydro: 10,
            electro: 20,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    GroundedGeoshroom: new DbObjectEnemy({
        name: 'grounded_geoshroom',
        serializeId: 162,
        iconClass: "type-magical enemy-icon-fungus-amanita-du-udatta-rock",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 30,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 30,
        },
    }),

    BlessboneRedVulture: new DbObjectEnemy({
        name: 'blessbone_red_vulture',
        serializeId: 167,
        iconClass: "type-magical enemy-icon-vulture-sacred-fire",
        resistances: {
            phys: 40,
            pyro: 70,
            dendro: 40,
            hydro: 40,
            electro: 40,
            anemo: 40,
            cryo: 40,
            geo: 40,
        },
        conditions: [
            new ConditionBoolean({
                name: 'consecrated_beast_sunned',
                serializeId: 1,
                title: 'talent_name.consecrated_beast_sunned',
                description: 'talent_descr.consecrated_beast_sunned',
                stats: {
                    enemy_res_phys: -30,
                    enemy_res_pyro: -60,
                    enemy_res_dendro: -30,
                    enemy_res_hydro: -30,
                    enemy_res_electro: -30,
                    enemy_res_anemo: -30,
                    enemy_res_cryo: -30,
                    enemy_res_geo: -30,
                },
            }),
        ],
    }),
    BlessboneScorpion: new DbObjectEnemy({
        name: 'blessbone_scorpion',
        serializeId: 168,
        iconClass: "type-magical enemy-icon-scorpion-sacred-electric",
        resistances: {
            phys: 40,
            pyro: 40,
            dendro: 40,
            hydro: 40,
            electro: 70,
            anemo: 40,
            cryo: 40,
            geo: 40,
        },
        conditions: [
            new ConditionBoolean({
                name: 'consecrated_beast_sunned',
                serializeId: 1,
                title: 'talent_name.consecrated_beast_sunned',
                description: 'talent_descr.consecrated_beast_sunned',
                stats: {
                    enemy_res_phys: -30,
                    enemy_res_pyro: -30,
                    enemy_res_dendro: -30,
                    enemy_res_hydro: -30,
                    enemy_res_electro: -60,
                    enemy_res_anemo: -30,
                    enemy_res_cryo: -30,
                    enemy_res_geo: -30,
                },
            }),
        ],
    }),
    BlessboneFlyingSerpent: new DbObjectEnemy({
        name: 'blessbone_flying_serpent',
        serializeId: 169,
        iconClass: "type-magical enemy-icon-chrysopelea-sacred-wind",
        resistances: {
            phys: 40,
            pyro: 40,
            dendro: 40,
            hydro: 40,
            electro: 40,
            anemo: 70,
            cryo: 40,
            geo: 40,
        },
        conditions: [
            new ConditionBoolean({
                name: 'consecrated_beast_sunned',
                serializeId: 1,
                title: 'talent_name.consecrated_beast_sunned',
                description: 'talent_descr.consecrated_beast_sunned',
                stats: {
                    enemy_res_phys: -30,
                    enemy_res_pyro: -30,
                    enemy_res_dendro: -30,
                    enemy_res_hydro: -30,
                    enemy_res_electro: -30,
                    enemy_res_anemo: -60,
                    enemy_res_cryo: -30,
                    enemy_res_geo: -30,
                },
            }),
        ],
    }),
    ConsecratedHornedCrocodile: new DbObjectEnemy({
        name: 'consecrated_horned_crocodile',
        serializeId: 176,
        iconClass: "type-magical enemy-icon-gator-sacred-water",
        resistances: {
            phys: 40,
            pyro: 40,
            dendro: 40,
            hydro: 70,
            electro: 40,
            anemo: 40,
            cryo: 40,
            geo: 40,
        },
        conditions: [
            new ConditionBoolean({
                name: 'consecrated_beast_sunned',
                serializeId: 1,
                title: 'talent_name.consecrated_beast_sunned',
                description: 'talent_descr.consecrated_beast_sunned',
                stats: {
                    enemy_res_phys: -30,
                    enemy_res_pyro: -30,
                    enemy_res_dendro: -30,
                    enemy_res_hydro: -60,
                    enemy_res_electro: -30,
                    enemy_res_anemo: -30,
                    enemy_res_cryo: -30,
                    enemy_res_geo: -30,
                },
            }),
        ],
    }),
    ConsecratedFangedBeast: new DbObjectEnemy({
        name: 'consecrated_fanged_beast',
        serializeId: 177,
        iconClass: "type-magical enemy-icon-panther-sacred-grass",
        resistances: {
            phys: 40,
            pyro: 40,
            dendro: 70,
            hydro: 40,
            electro: 40,
            anemo: 40,
            cryo: 40,
            geo: 40,
        },
        conditions: [
            new ConditionBoolean({
                name: 'consecrated_beast_sunned',
                serializeId: 1,
                title: 'talent_name.consecrated_beast_sunned',
                description: 'talent_descr.consecrated_beast_sunned',
                stats: {
                    enemy_res_phys: -30,
                    enemy_res_pyro: -30,
                    enemy_res_dendro: -60,
                    enemy_res_hydro: -30,
                    enemy_res_electro: -30,
                    enemy_res_anemo: -30,
                    enemy_res_cryo: -30,
                    enemy_res_geo: -30,
                },
            }),
        ],
    }),
    SetekhWenut: new DbObjectEnemy({
        name: 'setekh_wenut',
        serializeId: 170,
        iconClass: "type-magical enemy-icon-sandworm",
        resistances: {
            phys: 25,
            pyro: 25,
            dendro: 25,
            hydro: 25,
            electro: 25,
            anemo: 60,
            cryo: 25,
            geo: 25,
        },
        conditions: [
            new ConditionBoolean({
                name: 'setekh_wenut_abyss',
                serializeId: 2,
                title: 'talent_name.spiral_abyss_buff',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 30,
                    enemy_res_pyro: 30,
                    enemy_res_dendro: 30,
                    enemy_res_hydro: 30,
                    enemy_res_electro: 30,
                    enemy_res_anemo: 30,
                    enemy_res_cryo: 30,
                    enemy_res_geo: 30,
                },
            }),
            new ConditionDropdownElement({
                name: 'setekh_wenut_paralized',
                serializeId: 1,
                multiple: true,
                hideEmpty: true,
                dropdownClass: 'select-element-multiple',
                title: 'talent_name.setekh_wenut_paralized',
                description: 'talent_descr.setekh_wenut_paralized',
                values: [
                    {
                        value: 'cryo',
                        serializeId: 1,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_cryo: -20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'electro',
                        serializeId: 2,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_electro: -20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'hydro',
                        serializeId: 3,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_hydro: -20,
                                },
                            }),
                        ],
                    },
                    {
                        value: 'pyro',
                        serializeId: 4,
                        conditions: [
                            new Condition({
                                stats: {
                                    enemy_res_pyro: -20,
                                },
                            }),
                        ],
                    },
                ],
            }),
        ],
    }),
    HuntersRay: new DbObjectEnemy({
        name: 'hunters_ray',
        serializeId: 197,
        iconClass: "type-magical enemy-icon-mantaray-larva-01",
        resistances: defaultRes,
    }),
    ArmoredCrab: new DbObjectEnemy({
        name: 'armored_crab',
        serializeId: 198,
        iconClass: "type-magical enemy-icon-hermitcrab-larva-01",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    Blubberbeast: new DbObjectEnemy({
        name: 'blubberbeast',
        serializeId: 199,
        iconClass: "type-magical enemy-icon-seal-larva-01",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    HatJellyfish: new DbObjectEnemy({
        name: 'hat_jellyfish',
        serializeId: 200,
        iconClass: "type-magical enemy-icon-jellyfish-larva-01",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    BubblySeahorse: new DbObjectEnemy({
        name: 'bubbly_seahorse',
        serializeId: 201,
        iconClass: "type-magical enemy-icon-seahorse-larva-01",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    BallOctopus: new DbObjectEnemy({
        name: 'ball_octopus',
        serializeId: 202,
        iconClass: "type-magical enemy-icon-octopus-larva-01",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    AngelicSeaHare: new DbObjectEnemy({
        name: 'angelic_sea_hare',
        serializeId: 203,
        iconClass: "type-magical enemy-icon-aplysia-larva-01",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    SternshieldCrab: new DbObjectEnemy({
        name: 'sternshield_crab',
        serializeId: 204,
        iconClass: "type-magical enemy-icon-hermitcrab-mature",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    CherubicSeaHare: new DbObjectEnemy({
        name: 'cherubic_sea_hare',
        serializeId: 205,
        iconClass: "type-magical enemy-icon-aplysia-mature",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    BubblerSeahorse: new DbObjectEnemy({
        name: 'bubbler_seahorse',
        serializeId: 206,
        iconClass: "type-magical enemy-icon-seahorse-mature",
        resistances: defaultRes,
        conditions: [fontemer_aberrant_shielded],
    }),
    EmperorofFireandIron: new DbObjectEnemy({
        name: 'emperor_of_fire_and_iron',
        serializeId: 207,
        iconClass: "type-magical enemy-icon-hermitcrab-primo",
        resistances: {
            phys: 10,
            pyro: 60,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [fontemer_aberrant_shielded],
    }),
    MillennialPearlSeahorse: new DbObjectEnemy({
        name: 'millennial_pearl_seahorse',
        serializeId: 210,
        iconClass: "type-magical enemy-icon-seahorse-primo-electric",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 60,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'boss_begin_fight',
                serializeId: 1,
                title: 'talent_name.boss_begin_fight',
                description: 'talent_descr.boss_begin_fight',
                stats: {
                    enemy_res_phys: 200,
                    enemy_res_pyro: 200,
                    enemy_res_dendro: 200,
                    enemy_res_hydro: 200,
                    enemy_res_electro: 200,
                    enemy_res_anemo: 200,
                    enemy_res_cryo: 200,
                    enemy_res_geo: 200,
                },
            }),
            new ConditionBoolean({
                name: 'regisvine_shielded',
                serializeId: 2,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 60,
                    enemy_res_pyro: 60,
                    enemy_res_dendro: 60,
                    enemy_res_hydro: 60,
                    enemy_res_electro: 60,
                    enemy_res_anemo: 60,
                    enemy_res_cryo: 60,
                    enemy_res_geo: 60,
                },
            }),
        ],
    }),
    XuanwenBeast: new DbObjectEnemy({
        name: 'xuanwen_beast',
        serializeId: 215,
        iconClass: "type-magical enemy-icon-striped",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 50,
            cryo: 10,
            geo: 10,
        },
    }),
    SolitarySuanni: new DbObjectEnemy({
        name: 'solitary_suanni',
        serializeId: 216,
        iconClass: "type-magical enemy-icon-hermit",
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 70,
            electro: 10,
            anemo: 70,
            cryo: 10,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'solitary_suanni_rage',
                serializeId: 1,
                title: 'talent_name.solitary_suanni_rage',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 200,
                    enemy_res_pyro: 200,
                    enemy_res_dendro: 200,
                    enemy_res_hydro: 200,
                    enemy_res_electro: 200,
                    enemy_res_anemo: 200,
                    enemy_res_cryo: 200,
                    enemy_res_geo: 200,
                },
            }),
        ],
    }),
    PraetorianGolem: new DbObjectEnemy({
        name: 'praetorian_golem',
        serializeId: 227,
        iconClass: "type-magical enemy-icon-golem-legion",
        resistances: defaultRes,
        conditions: [
            new ConditionBoolean({
                name: 'enemy_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 50,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
        ],
    }),
    LegatusGolem: new DbObjectEnemy({
        name: 'legatus_golem',
        serializeId: 228,
        iconClass: "type-magical enemy-icon-golem-centaur",
        resistances: defaultRes,
        conditions: [
            new ConditionBoolean({
                name: 'enemy_shielded',
                serializeId: 1,
                title: 'talent_name.regisvine_shielded',
                description: 'talent_descr.regisvine_shielded',
                stats: {
                    enemy_res_phys: 60,
                    enemy_res_pyro: 60,
                    enemy_res_dendro: 60,
                    enemy_res_hydro: 60,
                    enemy_res_electro: 60,
                    enemy_res_anemo: 60,
                    enemy_res_cryo: 60,
                    enemy_res_geo: 60,
                },
            }),
            new ConditionBoolean({
                name: 'spiral_abyss_buff',
                serializeId: 2,
                title: 'talent_name.spiral_abyss_buff',
                description: 'talent_descr.buff_all_resistances',
                stats: {
                    enemy_res_phys: 30,
                    enemy_res_pyro: 30,
                    enemy_res_dendro: 30,
                    enemy_res_hydro: 30,
                    enemy_res_electro: 30,
                    enemy_res_anemo: 30,
                    enemy_res_cryo: 30,
                    enemy_res_geo: 30,
                },
                subConditions: [
                    new ConditionBoolean({name: 'enemy_shielded'}),
                    new ConditionNot([
                        new ConditionBoolean({name: 'enemy_stunned'}),
                    ]),
                ],
            }),
            new ConditionBoolean({
                name: 'enemy_stunned',
                serializeId: 3,
                title: 'talent_name.enemy_stunned',
                description: 'talent_descr.enemy_stunned_res',
                stats: {
                    enemy_res_phys: -80,
                    enemy_res_pyro: -80,
                    enemy_res_dendro: -80,
                    enemy_res_hydro: -80,
                    enemy_res_electro: -80,
                    enemy_res_anemo: -80,
                    enemy_res_cryo: -80,
                    enemy_res_geo: -80,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'enemy_shielded'}),
                    ]),
                ],
            }),
        ],
    }),
    TepetlisaurWhelp: new DbObjectEnemy({
        name: 'tepetlisaur_whelp',
        serializeId: 245,
        iconClass: 'type-magical enemy-icon-natsaurus-drillhead-small',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 30,
        },
    }),
    Tepetlisaurus: new DbObjectEnemy({
        name: 'tepetlisaurus',
        serializeId: 246,
        iconClass: 'type-magical enemy-icon-natsaurus-drillhead-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    KoholasaurWhelp: new DbObjectEnemy({
        name: 'koholasaur_whelp',
        serializeId: 247,
        iconClass: 'type-magical enemy-icon-natsaurus-mosasaurus-small',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 30,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Koholasaurus: new DbObjectEnemy({
        name: 'koholasaurus',
        serializeId: 248,
        iconClass: 'type-magical enemy-icon-natsaurus-mosasaurus-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    YumkasaurWhelp: new DbObjectEnemy({
        name: 'yumkasaur_whelp',
        serializeId: 249,
        iconClass: 'type-magical enemy-icon-natsaurus-hookwalker-small',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 30,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Yumkasaurus: new DbObjectEnemy({
        name: 'yumkasaurus',
        serializeId: 250,
        iconClass: 'type-magical enemy-icon-natsaurus-hookwalker-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 50,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    GluttonousYumkasaurMountainKing: new DbObjectEnemy({
        name: 'gluttonous_yumkasaur_mountain_king',
        serializeId: 251,
        iconClass: 'type-magical enemy-icon-natsaurus-hookwalker-primo',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 70,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    GoldflameQucusaurTyrant: new DbObjectEnemy({
        name: 'gold_flame_qucusaur_tyrant',
        serializeId: 252,
        iconClass: 'type-magical enemy-icon-natsaurus-flamingo-primo',
        resistances: {
            phys: 10,
            pyro: 70,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    RockCavernousWayobManifestation: new DbObjectEnemy({
        name: 'rock_cavernous_wayob_manifestation',
        serializeId: 253,
        iconClass: 'type-magical enemy-icon-wayob-drillhead',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
    FlowInvertedWayobManifestation: new DbObjectEnemy({
        name: 'flow_inverted_wayob_manifestation',
        serializeId: 254,
        iconClass: 'type-magical enemy-icon-wayob-mosasaurus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 50,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    FoliarSwiftWayobManifestation: new DbObjectEnemy({
        name: 'foliar_swift_wayob_manifestation',
        serializeId: 255,
        iconClass: 'type-magical enemy-icon-wayob-hookwalker',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 50,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    FluidAvatarofLava: new DbObjectEnemy({
        name: 'fluid_avatar_of_lava',
        serializeId: 256,
        iconClass: 'type-magical enemy-icon-lava-liquid',
        resistances: {
            phys: 10,
            pyro: 70,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ErodingAvatarofLava: new DbObjectEnemy({
        name: 'eroding_avatar_of_lava',
        serializeId: 257,
        iconClass: 'type-magical enemy-icon-lava-solid',
        resistances: defaultRes,
    }),
    QucusaurusChick: new DbObjectEnemy({
        name: 'qucusaurus_chick',
        serializeId: 294,
        iconClass: 'type-magical enemy-icon-natsaurus-flamingo-small',
        resistances: {
            phys: 10,
            pyro: 30,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Qucusaurus: new DbObjectEnemy({
        name: 'qucusaurus',
        serializeId: 295,
        iconClass: 'type-magical enemy-icon-natsaurus-flamingo-normal',
        resistances: {
            phys: 10,
            pyro: 50,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    IktomisaurusChick: new DbObjectEnemy({
        name: 'iktomisaurus_chick',
        serializeId: 296,
        iconClass: 'type-magical enemy-icon-natsaurus-shamansaurus-small',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 30,
            geo: 10,
        },
    }),
    Iktomisaurus: new DbObjectEnemy({
        name: 'iktomisaurus',
        serializeId: 297,
        iconClass: 'type-magical enemy-icon-natsaurus-shamansaurus-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    BitingColdWayobManifestation: new DbObjectEnemy({
        name: 'biting_cold_wayob_manifestation',
        serializeId: 298,
        iconClass: 'type-magical enemy-icon-wayob-shamansaurus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 50,
            geo: 10,
        },
    }),
    BurningAflameWayobManifestation: new DbObjectEnemy({
        name: 'burning_aflame_wayob_manifestation',
        serializeId: 299,
        iconClass: 'type-magical enemy-icon-wayob-flamingo',
        resistances: {
            phys: 10,
            pyro: 50,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),

    TatankasaurWhelp: new DbObjectEnemy({
        name: 'tatankasaur_whelp',
        serializeId: 307,
        iconClass: 'type-magical enemy-icon-natsaurus-bisonsaurus-small',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 30,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    Tatankasaurus: new DbObjectEnemy({
        name: 'tatankasaur',
        serializeId: 308,
        iconClass: 'type-magical enemy-icon-natsaurus-bisonsaurus-normal',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 50,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),
    ThunderingWayobManifestation: new DbObjectEnemy({
        name: 'thundering_wayob_manifestation',
        serializeId: 309,
        iconClass: 'type-magical enemy-icon-wayob-bisonsaurus',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 50,
            anemo: 10,
            cryo: 10,
            geo: 10,
        },
    }),

    LavaDragonStatue: new DbObjectEnemy({
        name: 'lava_dragon_statue',
        serializeId: 310,
        iconClass: 'type-magical enemy-icon-lavatitan',
        resistances: {
            phys: 70,
            pyro: 70,
            dendro: 70,
            hydro: 70,
            electro: 70,
            anemo: 70,
            cryo: 70,
            geo: 70,
        },
        conditions: [
            new ConditionBoolean({
                name: 'spiral_abyss_buff',
                serializeId: 3,
                title: 'talent_name.spiral_abyss_buff',
                stats: {
                    enemy_res_phys: 80,
                    enemy_res_pyro: 80,
                    enemy_res_dendro: 80,
                    enemy_res_hydro: 80,
                    enemy_res_electro: 80,
                    enemy_res_anemo: 80,
                    enemy_res_cryo: 80,
                    enemy_res_geo: 80,
                },
            }),
            new ConditionBoolean({
                name: 'enemy_molten_state',
                serializeId: 1,
                title: 'talent_name.enemy_molten_state',
                description: 'talent_descr.enemy_molten_state',
            }),
            new ConditionBoolean({
                name: 'enemy_overburn_state',
                serializeId: 2,
                title: 'talent_name.enemy_overburn_state',
                description: 'talent_descr.enemy_overburn_state',
                condition: new ConditionNot([
                    new ConditionBoolean({name: 'enemy_molten_state'}),
                ]),
            }),
            new Condition({
                stats: {
                    enemy_res_phys: -100,
                    enemy_res_dendro: -100,
                    enemy_res_hydro: -100,
                    enemy_res_electro: -100,
                    enemy_res_anemo: -100,
                    enemy_res_cryo: -100,
                    enemy_res_geo: -100,
                },
                condition: new ConditionAnd([
                    new ConditionBoolean({name: "enemy_molten_state"}),
                    new ConditionNot([new ConditionBoolean({name: "spiral_abyss_buff"})]),
                ]),
            }),
            new Condition({
                stats: {
                    enemy_res_phys: -130,
                    enemy_res_pyro: -130,
                    enemy_res_dendro: -130,
                    enemy_res_hydro: -130,
                    enemy_res_electro: -130,
                    enemy_res_anemo: -130,
                    enemy_res_cryo: -130,
                    enemy_res_geo: -130,
                },
                condition: new ConditionAnd([
                    new ConditionBoolean({name: "enemy_overburn_state"}),
                    new ConditionNot([new ConditionBoolean({name: "spiral_abyss_buff"})]),
                    new ConditionNot([new ConditionBoolean({name: "enemy_molten_state"})]),
                ]),
            }),
            new Condition({
                stats: {
                    enemy_res_phys: -105,
                    enemy_res_dendro: -105,
                    enemy_res_hydro: -105,
                    enemy_res_electro: -105,
                    enemy_res_anemo: -105,
                    enemy_res_cryo: -105,
                    enemy_res_geo: -105,
                },
                condition: new ConditionAnd([
                    new ConditionBoolean({name: "enemy_molten_state"}),
                    new ConditionBoolean({name: "spiral_abyss_buff"}),
                ]),
            }),
            new Condition({
                stats: {
                    enemy_res_phys: -140,
                    enemy_res_pyro: -140,
                    enemy_res_dendro: -140,
                    enemy_res_hydro: -140,
                    enemy_res_electro: -140,
                    enemy_res_anemo: -140,
                    enemy_res_cryo: -140,
                    enemy_res_geo: -140,
                },
                condition: new ConditionAnd([
                    new ConditionBoolean({name: "enemy_overburn_state"}),
                    new ConditionBoolean({name: "spiral_abyss_buff"}),
                    new ConditionNot([new ConditionBoolean({name: "enemy_molten_state"})]),
                ]),
            }),
        ],
    }),
    FurnaceShellMountainWeasel: new DbObjectEnemy({
        name: 'furnace_shell_mountain_weasel',
        serializeId: 311,
        iconClass: 'type-magical enemy-icon-volcanoweasel',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 10,
            geo: 50,
        },
    }),
});




