import { ConditionBoolean } from "../../classes/Condition/Boolean";
import { ConditionNot } from "../../classes/Condition/Not";
import { DbObjectEnemy } from "../../classes/DbObject/Enemy";
import { DbObjectListSerialize } from "../../classes/DbObject/List/Serialize";

const humanRes = {
    phys: -20,
    pyro: 10,
    dendro: 10,
    hydro: 10,
    electro: 10,
    anemo: 10,
    cryo: 10,
    geo: 10,
};

export const TreasureHoarders = new DbObjectListSerialize({
    TreasureHoarderElectroPotioneer: new DbObjectEnemy({
        name: 'treasure_hoarder_electro_potioneer',
        serializeId: 55,
        iconClass: "type-human enemy-icon-thoarder-male-chemist-electric-01",
        resistances: humanRes,
    }),
    TreasureHoarderCryoPotioneer: new DbObjectEnemy({
        name: 'treasure_hoarder_cryo_potioneer',
        serializeId: 56,
        iconClass: "type-human enemy-icon-thoarder-male-chemist-ice-01",
        resistances: humanRes,
    }),
    TreasureHoarderHydroPotioneer: new DbObjectEnemy({
        name: 'treasure_hoarder_hydro_potioneer',
        serializeId: 57,
        iconClass: "type-human enemy-icon-thoarder-male-chemist-water-01",
        resistances: humanRes,
    }),
    TreasureHoarderPyroPotioneer: new DbObjectEnemy({
        name: 'treasure_hoarder_pyro_potioneer',
        serializeId: 58,
        iconClass: "type-human enemy-icon-thoarder-male-chemist-fire-01",
        resistances: humanRes,
    }),
    TreasureHoarderCrusher: new DbObjectEnemy({
        name: 'treasure_hoarder_crusher',
        serializeId: 59,
        iconClass: "type-human enemy-icon-thoarder-muscleman-miner-01",
        resistances: humanRes,
    }),
    TreasureHoarderGravedigger: new DbObjectEnemy({
        name: 'treasure_hoarder_gravedigger',
        serializeId: 60,
        iconClass: "type-human enemy-icon-thoarder-male-rogue-fat-02",
        resistances: humanRes,
    }),
    TreasureHoarderMarksman: new DbObjectEnemy({
        name: 'treasure_hoarder_marksman',
        serializeId: 61,
        iconClass: "type-human enemy-icon-thoarder-male-hunter-01",
        resistances: humanRes,
    }),
    TreasureHoarderScout: new DbObjectEnemy({
        name: 'treasure_hoarder_scout',
        serializeId: 62,
        iconClass: "type-human enemy-icon-thoarder-male-rogue-01",
        resistances: humanRes,
    }),
    TreasureHoarderHandyman: new DbObjectEnemy({
        name: 'treasure_hoarder_handyman',
        serializeId: 63,
        iconClass: "type-human enemy-icon-thoarder-male-rogue-fat-01",
        resistances: humanRes,
    }),
    TreasureHoarderPugilist: new DbObjectEnemy({
        name: 'treasure_hoarder_pugilist',
        serializeId: 64,
        iconClass: "type-human enemy-icon-thoarder-muscleman-boxer-01",
        resistances: humanRes,
    }),
    TreasureHoarderSeaman: new DbObjectEnemy({
        name: 'treasure_hoarder_seaman',
        serializeId: 65,
        iconClass: "type-human enemy-icon-thoarder-male-sailor-01",
        resistances: humanRes,
    }),
    NobushiJintouban: new DbObjectEnemy({
        name: 'nobushi_jintouban',
        serializeId: 103,
        iconClass: "type-human enemy-icon-samurai-ronin-01",
        resistances: humanRes,
    }),
    NobushiHitsukeban: new DbObjectEnemy({
        name: 'nobushi_hitsukeban',
        serializeId: 104,
        iconClass: "type-human enemy-icon-samurai-ronin-02",
        resistances: humanRes,
    }),
    NobushiKikouban: new DbObjectEnemy({
        name: 'nobushi_kikouban',
        serializeId: 105,
        iconClass: "type-human enemy-icon-samurai-ronin-03",
        resistances: humanRes,
    }),
    KairagiDancingThunder: new DbObjectEnemy({
        name: 'kairagi_dancing_thunder',
        serializeId: 106,
        iconClass: "type-human enemy-icon-samurai-kairagi-01",
        resistances: humanRes,
    }),
    KairagiFieryMight: new DbObjectEnemy({
        name: 'kairagi_fiery_might',
        serializeId: 107,
        iconClass: "type-human enemy-icon-samurai-kairagi-02",
        resistances: humanRes,
    }),
    EremiteAxeVanguard: new DbObjectEnemy({
        name: 'eremite_axe_vanguard',
        serializeId: 133,
        iconClass: "type-human enemy-icon-eremite-axe-vanguard",
        resistances: humanRes,
    }),
    EremiteCrossbow: new DbObjectEnemy({
        name: 'eremite_crossbow',
        serializeId: 134,
        iconClass: "type-human enemy-icon-eremite-crossbow",
        resistances: humanRes,
    }),
    EremiteRavenbeakHalberdier: new DbObjectEnemy({
        name: 'eremite_ravenbeak_halberdier',
        serializeId: 135,
        iconClass: "type-human enemy-icon-eremite-ravenbeak-halberdier",
        resistances: humanRes,
    }),
    EremiteLinebreaker: new DbObjectEnemy({
        name: 'eremite_linebreaker',
        serializeId: 136,
        iconClass: "type-human enemy-icon-eremite-linebreaker",
        resistances: humanRes,
    }),
    EremiteSwordDancer: new DbObjectEnemy({
        name: 'eremite_sword_dancer',
        serializeId: 137,
        iconClass: "type-human enemy-icon-eremite-sword-dancer",
        resistances: humanRes,
    }),
    EremiteDesertClearwater: new DbObjectEnemy({
        name: 'eremite_desert_clearwater',
        serializeId: 138,
        iconClass: "type-human enemy-icon-eremite-desert-clearwater",
        resistances: humanRes,
    }),
    EremiteSunfrost: new DbObjectEnemy({
        name: 'eremite_sunfrost',
        serializeId: 139,
        iconClass: "type-human enemy-icon-eremite-sunfrost",
        resistances: humanRes,
    }),
    EremiteDaythunder: new DbObjectEnemy({
        name: 'eremite_daythunder',
        serializeId: 140,
        iconClass: "type-human enemy-icon-eremite-daythunder",
        resistances: humanRes,
    }),
    EremiteGalehunter: new DbObjectEnemy({
        name: 'eremite_galehunter',
        serializeId: 157,
        iconClass: "type-human enemy-icon-eremite-female-standard-longbow",
        resistances: humanRes,
        conditions: [
            new ConditionBoolean({
                name: 'eremite_enhanced',
                serializeId: 1,
                title: 'talent_name.eremite_enhanced',
                description: 'talent_descr.eremite_enhanced',
                stats: {
                    enemy_res_phys: 60,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
            new ConditionBoolean({
                name: 'eremite_stunned',
                serializeId: 2,
                title: 'talent_name.eremite_stunned',
                description: 'talent_descr.eremite_stunned_anemo',
                stats: {
                    enemy_res_anemo: -50,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'eremite_enhanced'}),
                    ]),
                ],
            }),
        ],
    }),
    EremiteStoneEnchanter: new DbObjectEnemy({
        name: 'eremite_stone_enchanter',
        serializeId: 158,
        iconClass: "type-human enemy-icon-eremite-male-strong-katar",
        resistances: humanRes,
        conditions: [
            new ConditionBoolean({
                name: 'eremite_enhanced',
                serializeId: 1,
                title: 'talent_name.eremite_enhanced',
                description: 'talent_descr.eremite_enhanced',
                stats: {
                    enemy_res_phys: 60,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
            new ConditionBoolean({
                name: 'eremite_stunned',
                serializeId: 2,
                title: 'talent_name.eremite_stunned',
                description: 'talent_descr.eremite_stunned_geo',
                stats: {
                    enemy_res_geo: -50,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'eremite_enhanced'}),
                    ]),
                ],
            }),
        ],
    }),
    EremiteScorchingLoremaster: new DbObjectEnemy({
        name: 'eremite_scorching_loremaster',
        serializeId: 165,
        iconClass: "type-human enemy-icon-eremite-female-standard-oracle",
        resistances: humanRes,
        conditions: [
            new ConditionBoolean({
                name: 'eremite_enhanced',
                serializeId: 1,
                title: 'talent_name.eremite_enhanced',
                description: 'talent_descr.eremite_enhanced',
                stats: {
                    enemy_res_phys: 60,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
            new ConditionBoolean({
                name: 'eremite_stunned',
                serializeId: 2,
                title: 'talent_name.eremite_stunned',
                description: 'talent_descr.eremite_stunned_pyro',
                stats: {
                    enemy_res_pyro: -50,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'eremite_enhanced'}),
                    ]),
                ],
            }),
        ],
    }),
    EremiteFloralRingDancer: new DbObjectEnemy({
        name: 'eremite_floral_ring_dancer',
        serializeId: 166,
        iconClass: "type-human enemy-icon-eremite-female-standard-dancer",
        resistances: humanRes,
        conditions: [
            new ConditionBoolean({
                name: 'eremite_enhanced',
                serializeId: 1,
                title: 'talent_name.eremite_enhanced',
                description: 'talent_descr.eremite_enhanced',
                stats: {
                    enemy_res_phys: 60,
                    enemy_res_pyro: 50,
                    enemy_res_dendro: 50,
                    enemy_res_hydro: 50,
                    enemy_res_electro: 50,
                    enemy_res_anemo: 50,
                    enemy_res_cryo: 50,
                    enemy_res_geo: 50,
                },
            }),
            new ConditionBoolean({
                name: 'eremite_stunned',
                serializeId: 2,
                title: 'talent_name.eremite_stunned',
                description: 'talent_descr.eremite_stunned_dendro',
                stats: {
                    enemy_res_dendro: -50,
                },
                subConditions: [
                    new ConditionNot([
                        new ConditionBoolean({name: 'eremite_enhanced'}),
                    ]),
                ],
            }),
        ],
    }),
    FlowingBladeSkirmisher: new DbObjectEnemy({
        name: 'flowing_blade_skirmisher',
        serializeId: 230,
        iconClass: "type-human enemy-icon-tribalwarrior-launcher-mosasaurus",
        resistances: humanRes,
    }),
    ForgedSandInterrogator: new DbObjectEnemy({
        name: 'forged_sand_interrogator',
        serializeId: 231,
        iconClass: "type-human enemy-icon-human-fat-noweapon-drillhead",
        resistances: humanRes,
    }),
    SwiftstepSeeker: new DbObjectEnemy({
        name: 'swiftstep_seeker',
        serializeId: 232,
        iconClass: "type-human enemy-icon-human-female-sword-hookwalker",
        resistances: humanRes,
    }),
    SwiftstepStormScout: new DbObjectEnemy({
        name: 'swiftstep_storm_scout',
        serializeId: 233,
        iconClass: "type-human enemy-icon-human-male-claymore-hookwalker",
        resistances: humanRes,
    }),
    FlowingBladeGreaseSaw: new DbObjectEnemy({
        name: 'flowing_blade_grease_saw',
        serializeId: 234,
        iconClass: "type-human enemy-icon-human-male-sword-mosasaurus",
        resistances: humanRes,
    }),
    SwiftstepArmedCourier: new DbObjectEnemy({
        name: 'swiftstep_armed_courier',
        serializeId: 235,
        iconClass: "type-human enemy-icon-human-male-claymore-hookwalker",
        resistances: humanRes,
    }),
    ForgedSandShieldbreaker: new DbObjectEnemy({
        name: 'forged_sand_shieldbreaker',
        serializeId: 236,
        iconClass: 'type-human enemy-icon-human-muscleman-claymore-drillhead',
        resistances: humanRes,
    }),
    ForgedSandJavelineer: new DbObjectEnemy({
        name: 'forged_sand_javelineer',
        serializeId: 237,
        iconClass: 'type-human enemy-icon-human-fat-noweapon-drillhead',
        resistances: humanRes,
    }),
    FlowingBladeHarpoonThrower: new DbObjectEnemy({
        name: 'flowing_blade_harpoon_thrower',
        serializeId: 238,
        iconClass: 'type-human enemy-icon-human-fat-noweapon-mosasaurus',
        resistances: humanRes,
    }),
    TepetlisaurusWarriorShardStriker: new DbObjectEnemy({
        name: 'tepetlisaurus_warrior_shard_striker',
        serializeId: 239,
        iconClass: 'type-human enemy-icon-tribalwarrior-powermaul-drillhead',
        resistances: humanRes,
    }),
    TepetlisaurusWarriorRockbreakerBlade: new DbObjectEnemy({
        name: 'tepetlisaurus_warrior_rockbreaker_blade',
        serializeId: 240,
        iconClass: 'type-human enemy-icon-tribalwarrior-chainsword-drillhead',
        resistances: humanRes,
    }),
    YumkasaurusWarriorWhirlingLeaves: new DbObjectEnemy({
        name: 'yumkasaurus_warrior_whirling_leaves',
        serializeId: 241,
        iconClass: 'type-human enemy-icon-tribalwarrior-chainsword-hookwalker',
        resistances: humanRes,
    }),
    YumkasaurusWarriorFlowingSkyfire: new DbObjectEnemy({
        name: 'yumkasaurus_warrior_flowing_skyfire',
        serializeId: 242,
        iconClass: 'type-human enemy-icon-tribalwarrior-launcher-hookwalker',
        resistances: humanRes,
    }),
    KoholasaurusWarriorWaveshuttler: new DbObjectEnemy({
        name: 'koholasaurus_warrior_waveshuttler',
        serializeId: 243,
        iconClass: 'type-human enemy-icon-tribalwarrior-slingshot-mosasaurus',
        resistances: humanRes,
    }),
    KoholasaurusWarriorReefsplitter: new DbObjectEnemy({
        name: 'koholasaurus_warrior_reefsplitter',
        serializeId: 244,
        iconClass: 'type-human enemy-icon-tribalwarrior-launcher-mosasaurus',
        resistances: humanRes,
    }),

    WingedWarriorSkysoarer: new DbObjectEnemy({
        name: 'winged_warrior_skysoarer',
        serializeId: 283,
        iconClass: 'type-human enemy-icon-human-female-noweapon-flamingo',
        resistances: humanRes,
    }),
    WingedWarriorFeathershedder: new DbObjectEnemy({
        name: 'winged_warrior_feathershedder',
        serializeId: 284,
        iconClass: 'type-human enemy-icon-human-female-sword-flamingo',
        resistances: humanRes,
    }),
    SpiritspeakerWarriorDeterminator: new DbObjectEnemy({
        name: 'spiritspeaker_warrior_determinator',
        serializeId: 285,
        iconClass: 'type-human enemy-icon-human-female-sword-shamansaurus',
        resistances: humanRes,
    }),
    SpiritspeakerWarriorPsychokinetic: new DbObjectEnemy({
        name: 'spiritspeaker_warrior_psychokinetic',
        serializeId: 286,
        iconClass: 'type-human enemy-icon-human-male-sword-shamansaurus',
        resistances: humanRes,
    }),
    SpiritspeakerWarriorContemplator: new DbObjectEnemy({
        name: 'spiritspeaker_warrior_contemplator',
        serializeId: 287,
        iconClass: 'type-human enemy-icon-human-male-claymore-shamansaurus',
        resistances: humanRes,
    }),
    WingedWarriorSkymaster: new DbObjectEnemy({
        name: 'winged_warrior_skymaster',
        serializeId: 288,
        iconClass: 'type-human enemy-icon-human-muscleman-claymore-flamingo',
        resistances: humanRes,
    }),
    QucusaurusWarriorHeartstarHammer: new DbObjectEnemy({
        name: 'qucusaurus_warrior_weartstar_hammer',
        serializeId: 289,
        iconClass: 'type-human enemy-icon-tribalwarrior-powermaul-flamingo',
        resistances: humanRes,
    }),
    QucusaurusWarriorBlazingSky: new DbObjectEnemy({
        name: 'qucusaurus_warrior_blazing_sky',
        serializeId: 290,
        iconClass: 'type-human enemy-icon-tribalwarrior-slingshot-flamingo',
        resistances: humanRes,
    }),
    IktomisaurusWarriorIcyTidebearer: new DbObjectEnemy({
        name: 'iktomisaurus_warrior_icy_tidebearer',
        serializeId: 291,
        iconClass: 'type-human enemy-icon-tribalwarrior-chainsword-shamansaurus',
        resistances: humanRes,
    }),
    IktomisaurusWarriorCryocrystalCannon: new DbObjectEnemy({
        name: 'iktomisaurus_warrior_cryocrystal_cannon',
        serializeId: 292,
        iconClass: 'type-human enemy-icon-tribalwarrior-launcher-shamansaurus',
        resistances: humanRes,
    }),
    WaywardHermeticSpiritspeaker: new DbObjectEnemy({
        name: 'wayward_hermetic_spiritspeaker',
        serializeId: 300,
        iconClass: 'type-human enemy-icon-tribalwarrior-udugan',
        resistances: {
            phys: 10,
            pyro: 10,
            dendro: 10,
            hydro: 10,
            electro: 10,
            anemo: 10,
            cryo: 70,
            geo: 10,
        },
        conditions: [
            new ConditionBoolean({
                name: 'enemy_stunned',
                serializeId: 1,
                title: 'talent_name.enemy_stunned',
                description: 'talent_descr.enemy_stunned_res',
                stats: {
                    enemy_res_phys: -40,
                    enemy_res_pyro: -40,
                    enemy_res_dendro: -40,
                    enemy_res_hydro: -40,
                    enemy_res_electro: -40,
                    enemy_res_anemo: -40,
                    enemy_res_cryo: -40,
                    enemy_res_geo: -40,
                },
            }),
        ],
    }),
    FerociousWarriorHumanRam: new DbObjectEnemy({
        name: 'ferocious_warrior_human_ram',
        serializeId: 302,
        iconClass: 'type-human enemy-icon-human-male-sword-bisonsaurus',
        resistances: humanRes,
    }),
    FerociousWarriorWrestler: new DbObjectEnemy({
        name: 'ferocious_warrior_wrestler',
        serializeId: 303,
        iconClass: 'type-human enemy-icon-human-muscleman-claymore-bisonsaurus',
        resistances: humanRes,
    }),
    FerociousWarriorGrappler: new DbObjectEnemy({
        name: 'ferocious_warrior_grappler',
        serializeId: 304,
        iconClass: 'type-human enemy-icon-human-fat-sword-bisonsaurus',
        resistances: humanRes,
    }),
    TatankasaurusWarriorSkybreaker: new DbObjectEnemy({
        name: 'tatankasaurus_warrior_skybreaker',
        serializeId: 305,
        iconClass: 'type-human enemy-icon-tribalwarrior-powermaul-bisonsaurus',
        resistances: humanRes,
    }),
    TatankasaurusWarriorSpiritlightChaser: new DbObjectEnemy({
        name: 'tatankasaurus_warrior_spiritlight_chaser',
        serializeId: 306,
        iconClass: 'type-human enemy-icon-tribalwarrior-slingshot-bisonsaurus',
        resistances: humanRes,
    }),
});
